// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const arriveAppointment = `-- name: ArriveAppointment :one
update appointments
set status = 'arrived'
where id = $1 and status = 'pending'
returning id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at
`

// Only a scheduled ('pending') appointment can arrive -- an unscheduled
// one has no date/time for a visit to have happened at. Frees the hold,
// same as ReleaseAppointment, since 'arrived' also falls outside
// appointments_one_active_hold_per_child's predicate.
func (q *Queries) ArriveAppointment(ctx context.Context, id int64) (Appointment, error) {
	row := q.db.QueryRow(ctx, arriveAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ChildID,
		&i.Session,
		&i.AgeRangeMinMonths,
		&i.AgeRangeMaxMonths,
		&i.SiblingComing,
		&i.ScheduleDate,
		&i.ScheduleTimeStart,
		&i.ScheduleTimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const createAppointment = `-- name: CreateAppointment :one
insert into appointments (experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming)
values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at
`

type CreateAppointmentParams struct {
	ExperimentID      int64          `json:"experiment_id"`
	ChildID           int64          `json:"child_id"`
	Session           int16          `json:"session"`
	AgeRangeMinMonths pgtype.Numeric `json:"age_range_min_months"`
	AgeRangeMaxMonths pgtype.Numeric `json:"age_range_max_months"`
	SiblingComing     string         `json:"sibling_coming"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ExperimentID,
		arg.ChildID,
		arg.Session,
		arg.AgeRangeMinMonths,
		arg.AgeRangeMaxMonths,
		arg.SiblingComing,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ChildID,
		&i.Session,
		&i.AgeRangeMinMonths,
		&i.AgeRangeMaxMonths,
		&i.SiblingComing,
		&i.ScheduleDate,
		&i.ScheduleTimeStart,
		&i.ScheduleTimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const createAppointmentExperimenter = `-- name: CreateAppointmentExperimenter :one
insert into appointment_experimenters (appointment_id, user_id, experiment_role_id, is_greeter)
values ($1, $2, $3, $4)
returning id, appointment_id, user_id, experiment_role_id, is_greeter
`

type CreateAppointmentExperimenterParams struct {
	AppointmentID    int64 `json:"appointment_id"`
	UserID           int64 `json:"user_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
	IsGreeter        bool  `json:"is_greeter"`
}

func (q *Queries) CreateAppointmentExperimenter(ctx context.Context, arg CreateAppointmentExperimenterParams) (AppointmentExperimenter, error) {
	row := q.db.QueryRow(ctx, createAppointmentExperimenter,
		arg.AppointmentID,
		arg.UserID,
		arg.ExperimentRoleID,
		arg.IsGreeter,
	)
	var i AppointmentExperimenter
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.UserID,
		&i.ExperimentRoleID,
		&i.IsGreeter,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
select id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at from appointments where id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id int64) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ChildID,
		&i.Session,
		&i.AgeRangeMinMonths,
		&i.AgeRangeMaxMonths,
		&i.SiblingComing,
		&i.ScheduleDate,
		&i.ScheduleTimeStart,
		&i.ScheduleTimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const getAppointmentLabID = `-- name: GetAppointmentLabID :one
select experiments.lab_id from appointments
join experiments on experiments.id = appointments.experiment_id
where appointments.id = $1
`

// For lab-membership authorization (mirrors GetConditionValueLabID):
// appointments has no lab_id of its own, so resolve it via the experiment.
func (q *Queries) GetAppointmentLabID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getAppointmentLabID, id)
	var lab_id int64
	err := row.Scan(&lab_id)
	return lab_id, err
}

const listAppointmentExperimenters = `-- name: ListAppointmentExperimenters :many
select id, appointment_id, user_id, experiment_role_id, is_greeter from appointment_experimenters where appointment_id = $1
`

func (q *Queries) ListAppointmentExperimenters(ctx context.Context, appointmentID int64) ([]AppointmentExperimenter, error) {
	rows, err := q.db.Query(ctx, listAppointmentExperimenters, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppointmentExperimenter
	for rows.Next() {
		var i AppointmentExperimenter
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.UserID,
			&i.ExperimentRoleID,
			&i.IsGreeter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByExperiment = `-- name: ListAppointmentsByExperiment :many
select id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at from appointments
where experiment_id = $1
  and ($2::text is null or status = $2)
order by created_at
`

type ListAppointmentsByExperimentParams struct {
	ExperimentID int64   `json:"experiment_id"`
	Status       *string `json:"status"`
}

func (q *Queries) ListAppointmentsByExperiment(ctx context.Context, arg ListAppointmentsByExperimentParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByExperiment, arg.ExperimentID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.ChildID,
			&i.Session,
			&i.AgeRangeMinMonths,
			&i.AgeRangeMaxMonths,
			&i.SiblingComing,
			&i.ScheduleDate,
			&i.ScheduleTimeStart,
			&i.ScheduleTimeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusyAppointmentExperimentersForDateRange = `-- name: ListBusyAppointmentExperimentersForDateRange :many
select appointment_experimenters.user_id, appointments.schedule_date,
       appointments.schedule_time_start, appointments.schedule_time_end
from appointment_experimenters
join appointments on appointments.id = appointment_experimenters.appointment_id
join experiments on experiments.id = appointments.experiment_id
where experiments.lab_id = $1
  and appointments.schedule_date between $2 and $3
  and appointments.status = 'pending'
`

type ListBusyAppointmentExperimentersForDateRangeParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ListBusyAppointmentExperimentersForDateRangeRow struct {
	UserID            int64       `json:"user_id"`
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	ScheduleTimeStart pgtype.Time `json:"schedule_time_start"`
	ScheduleTimeEnd   pgtype.Time `json:"schedule_time_end"`
}

// Members already committed to a Pending appointment within this date
// range in this lab, with the date and time range they're busy -- one
// query for a whole multi-day search rather than one call per candidate
// day; the caller groups rows by date in Go.
func (q *Queries) ListBusyAppointmentExperimentersForDateRange(ctx context.Context, arg ListBusyAppointmentExperimentersForDateRangeParams) ([]ListBusyAppointmentExperimentersForDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listBusyAppointmentExperimentersForDateRange, arg.LabID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusyAppointmentExperimentersForDateRangeRow
	for rows.Next() {
		var i ListBusyAppointmentExperimentersForDateRangeRow
		if err := rows.Scan(
			&i.UserID,
			&i.ScheduleDate,
			&i.ScheduleTimeStart,
			&i.ScheduleTimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusyEquipmentForDateRange = `-- name: ListBusyEquipmentForDateRange :many
select experiment_equipment_requirements.equipment_id, appointments.schedule_date,
       appointments.schedule_time_start, appointments.schedule_time_end
from experiment_equipment_requirements
join appointments on appointments.experiment_id = experiment_equipment_requirements.experiment_id
join experiments on experiments.id = appointments.experiment_id
where experiments.lab_id = $1
  and appointments.schedule_date between $2 and $3
  and appointments.status = 'pending'
`

type ListBusyEquipmentForDateRangeParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type ListBusyEquipmentForDateRangeRow struct {
	EquipmentID       int64       `json:"equipment_id"`
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	ScheduleTimeStart pgtype.Time `json:"schedule_time_start"`
	ScheduleTimeEnd   pgtype.Time `json:"schedule_time_end"`
}

// Equipment already required by a Pending appointment within this date
// range in this lab, with the date and time range it's in use -- counted
// against each equipment's quantity for that day's availability grid.
func (q *Queries) ListBusyEquipmentForDateRange(ctx context.Context, arg ListBusyEquipmentForDateRangeParams) ([]ListBusyEquipmentForDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listBusyEquipmentForDateRange, arg.LabID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusyEquipmentForDateRangeRow
	for rows.Next() {
		var i ListBusyEquipmentForDateRangeRow
		if err := rows.Scan(
			&i.EquipmentID,
			&i.ScheduleDate,
			&i.ScheduleTimeStart,
			&i.ScheduleTimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAppointment = `-- name: ReleaseAppointment :one
update appointments
set status = 'released'
where id = $1 and status in ('to_be_scheduled', 'pending')
returning id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at
`

// Deliberately allows releasing a 'pending' (already time-scheduled)
// appointment, not just an unscheduled one -- matches legacy's per-child
// release, which does the same. Frees the child up again: 'released'
// falls outside appointments_one_active_hold_per_child's predicate.
func (q *Queries) ReleaseAppointment(ctx context.Context, id int64) (Appointment, error) {
	row := q.db.QueryRow(ctx, releaseAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ChildID,
		&i.Session,
		&i.AgeRangeMinMonths,
		&i.AgeRangeMaxMonths,
		&i.SiblingComing,
		&i.ScheduleDate,
		&i.ScheduleTimeStart,
		&i.ScheduleTimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderSentAt,
	)
	return i, err
}

const scheduleAppointment = `-- name: ScheduleAppointment :one
update appointments
set schedule_date = $1,
    schedule_time_start = $2,
    schedule_time_end = $3,
    status = 'pending'
where id = $4
returning id, experiment_id, child_id, session, age_range_min_months, age_range_max_months, sibling_coming, schedule_date, schedule_time_start, schedule_time_end, status, created_at, updated_at, reminder_sent_at
`

type ScheduleAppointmentParams struct {
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	ScheduleTimeStart pgtype.Time `json:"schedule_time_start"`
	ScheduleTimeEnd   pgtype.Time `json:"schedule_time_end"`
	ID                int64       `json:"id"`
}

// Commits a chosen slot: the caller re-validates availability itself
// immediately before calling this (defensive re-check against staleness,
// since time passes between a search and a commit) -- this query just
// writes the result.
func (q *Queries) ScheduleAppointment(ctx context.Context, arg ScheduleAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, scheduleAppointment,
		arg.ScheduleDate,
		arg.ScheduleTimeStart,
		arg.ScheduleTimeEnd,
		arg.ID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.ChildID,
		&i.Session,
		&i.AgeRangeMinMonths,
		&i.AgeRangeMaxMonths,
		&i.SiblingComing,
		&i.ScheduleDate,
		&i.ScheduleTimeStart,
		&i.ScheduleTimeEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderSentAt,
	)
	return i, err
}
