// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"
	"net/netip"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
insert into audit_events (actor_user_id, lab_id, action, entity_type, entity_id, ip_address, metadata)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning id, occurred_at, actor_user_id, lab_id, action, entity_type, entity_id, ip_address, metadata
`

type CreateAuditEventParams struct {
	ActorUserID *int64      `json:"actor_user_id"`
	LabID       *int64      `json:"lab_id"`
	Action      string      `json:"action"`
	EntityType  *string     `json:"entity_type"`
	EntityID    *int64      `json:"entity_id"`
	IpAddress   *netip.Addr `json:"ip_address"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorUserID,
		arg.LabID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.IpAddress,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorUserID,
		&i.LabID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.IpAddress,
		&i.Metadata,
	)
	return i, err
}
