// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: children.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChild = `-- name: CreateChild :one
insert into children (
    family_id, first_name, last_name, sex, birth_date, due_date,
    gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie,
    birth_complications, twin, race_ethnicity, languages,
    recruitment_source_id, recruitment_source_other, response,
    created_by_user_id
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
)
returning id, family_id, first_name, last_name, sex, birth_date, due_date, gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie, birth_complications, twin, race_ethnicity, languages, recruitment_source_id, recruitment_source_other, response, created_by_user_id, deactivated_at, inactive_reason, created_at, updated_at, mcdi_percentile, mcdi_date
`

type CreateChildParams struct {
	FamilyID               int64          `json:"family_id"`
	FirstName              string         `json:"first_name"`
	LastName               string         `json:"last_name"`
	Sex                    string         `json:"sex"`
	BirthDate              pgtype.Date    `json:"birth_date"`
	DueDate                pgtype.Date    `json:"due_date"`
	GestationalAgeWeeks    pgtype.Numeric `json:"gestational_age_weeks"`
	BirthWeight            pgtype.Numeric `json:"birth_weight"`
	Apgar1                 *int16         `json:"apgar_1"`
	Apgar2                 *int16         `json:"apgar_2"`
	Premie                 *bool          `json:"premie"`
	BirthComplications     *bool          `json:"birth_complications"`
	Twin                   *bool          `json:"twin"`
	RaceEthnicity          []string       `json:"race_ethnicity"`
	Languages              []string       `json:"languages"`
	RecruitmentSourceID    *int64         `json:"recruitment_source_id"`
	RecruitmentSourceOther string         `json:"recruitment_source_other"`
	Response               string         `json:"response"`
	CreatedByUserID        int64          `json:"created_by_user_id"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, createChild,
		arg.FamilyID,
		arg.FirstName,
		arg.LastName,
		arg.Sex,
		arg.BirthDate,
		arg.DueDate,
		arg.GestationalAgeWeeks,
		arg.BirthWeight,
		arg.Apgar1,
		arg.Apgar2,
		arg.Premie,
		arg.BirthComplications,
		arg.Twin,
		arg.RaceEthnicity,
		arg.Languages,
		arg.RecruitmentSourceID,
		arg.RecruitmentSourceOther,
		arg.Response,
		arg.CreatedByUserID,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Sex,
		&i.BirthDate,
		&i.DueDate,
		&i.GestationalAgeWeeks,
		&i.BirthWeight,
		&i.Apgar1,
		&i.Apgar2,
		&i.Premie,
		&i.BirthComplications,
		&i.Twin,
		&i.RaceEthnicity,
		&i.Languages,
		&i.RecruitmentSourceID,
		&i.RecruitmentSourceOther,
		&i.Response,
		&i.CreatedByUserID,
		&i.DeactivatedAt,
		&i.InactiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.McdiPercentile,
		&i.McdiDate,
	)
	return i, err
}

const deactivateChild = `-- name: DeactivateChild :exec
update children set
    deactivated_at = now(),
    inactive_reason = $1
where id = $2
`

type DeactivateChildParams struct {
	InactiveReason string `json:"inactive_reason"`
	ID             int64  `json:"id"`
}

func (q *Queries) DeactivateChild(ctx context.Context, arg DeactivateChildParams) error {
	_, err := q.db.Exec(ctx, deactivateChild, arg.InactiveReason, arg.ID)
	return err
}

const getChildByID = `-- name: GetChildByID :one
select id, family_id, first_name, last_name, sex, birth_date, due_date, gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie, birth_complications, twin, race_ethnicity, languages, recruitment_source_id, recruitment_source_other, response, created_by_user_id, deactivated_at, inactive_reason, created_at, updated_at, mcdi_percentile, mcdi_date from children where id = $1
`

func (q *Queries) GetChildByID(ctx context.Context, id int64) (Child, error) {
	row := q.db.QueryRow(ctx, getChildByID, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Sex,
		&i.BirthDate,
		&i.DueDate,
		&i.GestationalAgeWeeks,
		&i.BirthWeight,
		&i.Apgar1,
		&i.Apgar2,
		&i.Premie,
		&i.BirthComplications,
		&i.Twin,
		&i.RaceEthnicity,
		&i.Languages,
		&i.RecruitmentSourceID,
		&i.RecruitmentSourceOther,
		&i.Response,
		&i.CreatedByUserID,
		&i.DeactivatedAt,
		&i.InactiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.McdiPercentile,
		&i.McdiDate,
	)
	return i, err
}

const listChildrenByFamily = `-- name: ListChildrenByFamily :many
select id, family_id, first_name, last_name, sex, birth_date, due_date, gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie, birth_complications, twin, race_ethnicity, languages, recruitment_source_id, recruitment_source_other, response, created_by_user_id, deactivated_at, inactive_reason, created_at, updated_at, mcdi_percentile, mcdi_date from children where family_id = $1 order by id
`

func (q *Queries) ListChildrenByFamily(ctx context.Context, familyID int64) ([]Child, error) {
	rows, err := q.db.Query(ctx, listChildrenByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.FirstName,
			&i.LastName,
			&i.Sex,
			&i.BirthDate,
			&i.DueDate,
			&i.GestationalAgeWeeks,
			&i.BirthWeight,
			&i.Apgar1,
			&i.Apgar2,
			&i.Premie,
			&i.BirthComplications,
			&i.Twin,
			&i.RaceEthnicity,
			&i.Languages,
			&i.RecruitmentSourceID,
			&i.RecruitmentSourceOther,
			&i.Response,
			&i.CreatedByUserID,
			&i.DeactivatedAt,
			&i.InactiveReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.McdiPercentile,
			&i.McdiDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChildren = `-- name: SearchChildren :many
select id, family_id, first_name, last_name, sex, birth_date, due_date, gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie, birth_complications, twin, race_ethnicity, languages, recruitment_source_id, recruitment_source_other, response, created_by_user_id, deactivated_at, inactive_reason, created_at, updated_at, mcdi_percentile, mcdi_date
from children
where
    ($1::text is null
        or word_similarity($1, first_name) > 0.2
        or word_similarity($1, last_name) > 0.2)
    and ($2::date is null or birth_date >= $2)
    and ($3::date is null or birth_date <= $3)
    and ($4::text is null or sex = $4)
    and ($5::boolean is null or twin = $5)
    and ($6::boolean is null or premie = $6)
    and ($7::text is null or languages @> array[$7]::text[])
    and ($8::bigint is null or family_id = $8)
    and ($9::boolean or deactivated_at is null)
order by
    greatest(
        word_similarity(coalesce($1, ''), first_name),
        word_similarity(coalesce($1, ''), last_name)
    ) desc,
    last_name,
    first_name
limit $10
`

type SearchChildrenParams struct {
	NameQuery          *string     `json:"name_query"`
	MinBirthDate       pgtype.Date `json:"min_birth_date"`
	MaxBirthDate       pgtype.Date `json:"max_birth_date"`
	Sex                *string     `json:"sex"`
	Twin               *bool       `json:"twin"`
	Premie             *bool       `json:"premie"`
	Language           *string     `json:"language"`
	FamilyID           *int64      `json:"family_id"`
	IncludeDeactivated bool        `json:"include_deactivated"`
	LimitCount         int32       `json:"limit_count"`
}

// Every filter is optional (sqlc.narg(x) is null or ...); passing none
// returns every child (subject to include_deactivated/limit_count).
//
// Name matching uses pg_trgm's word_similarity rather than plain
// similarity() or ILIKE: word_similarity scores how well the query matches
// *part of* the field, so a short query like "jhon" can still match
// "Johnathan" -- plain similarity() compares the whole strings and craters
// when they're very different lengths, and ILIKE only catches exact
// substrings, not typos. The 0.2 threshold is a literal in the query
// rather than the pg_trgm.similarity_threshold GUC (the %/<% operators'
// default is 0.3, too strict for short name fields, and overriding a GUC
// per-query risks leaking to the next query on a pooled connection).
func (q *Queries) SearchChildren(ctx context.Context, arg SearchChildrenParams) ([]Child, error) {
	rows, err := q.db.Query(ctx, searchChildren,
		arg.NameQuery,
		arg.MinBirthDate,
		arg.MaxBirthDate,
		arg.Sex,
		arg.Twin,
		arg.Premie,
		arg.Language,
		arg.FamilyID,
		arg.IncludeDeactivated,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.FirstName,
			&i.LastName,
			&i.Sex,
			&i.BirthDate,
			&i.DueDate,
			&i.GestationalAgeWeeks,
			&i.BirthWeight,
			&i.Apgar1,
			&i.Apgar2,
			&i.Premie,
			&i.BirthComplications,
			&i.Twin,
			&i.RaceEthnicity,
			&i.Languages,
			&i.RecruitmentSourceID,
			&i.RecruitmentSourceOther,
			&i.Response,
			&i.CreatedByUserID,
			&i.DeactivatedAt,
			&i.InactiveReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.McdiPercentile,
			&i.McdiDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChild = `-- name: UpdateChild :one
update children set
    first_name = $1,
    last_name = $2,
    sex = $3,
    birth_date = $4,
    due_date = $5,
    gestational_age_weeks = $6,
    birth_weight = $7,
    apgar_1 = $8,
    apgar_2 = $9,
    premie = $10,
    birth_complications = $11,
    twin = $12,
    race_ethnicity = $13,
    languages = $14,
    recruitment_source_id = $15,
    recruitment_source_other = $16,
    response = $17,
    mcdi_percentile = $18,
    mcdi_date = $19
where id = $20
returning id, family_id, first_name, last_name, sex, birth_date, due_date, gestational_age_weeks, birth_weight, apgar_1, apgar_2, premie, birth_complications, twin, race_ethnicity, languages, recruitment_source_id, recruitment_source_other, response, created_by_user_id, deactivated_at, inactive_reason, created_at, updated_at, mcdi_percentile, mcdi_date
`

type UpdateChildParams struct {
	FirstName              string         `json:"first_name"`
	LastName               string         `json:"last_name"`
	Sex                    string         `json:"sex"`
	BirthDate              pgtype.Date    `json:"birth_date"`
	DueDate                pgtype.Date    `json:"due_date"`
	GestationalAgeWeeks    pgtype.Numeric `json:"gestational_age_weeks"`
	BirthWeight            pgtype.Numeric `json:"birth_weight"`
	Apgar1                 *int16         `json:"apgar_1"`
	Apgar2                 *int16         `json:"apgar_2"`
	Premie                 *bool          `json:"premie"`
	BirthComplications     *bool          `json:"birth_complications"`
	Twin                   *bool          `json:"twin"`
	RaceEthnicity          []string       `json:"race_ethnicity"`
	Languages              []string       `json:"languages"`
	RecruitmentSourceID    *int64         `json:"recruitment_source_id"`
	RecruitmentSourceOther string         `json:"recruitment_source_other"`
	Response               string         `json:"response"`
	McdiPercentile         pgtype.Numeric `json:"mcdi_percentile"`
	McdiDate               pgtype.Date    `json:"mcdi_date"`
	ID                     int64          `json:"id"`
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, updateChild,
		arg.FirstName,
		arg.LastName,
		arg.Sex,
		arg.BirthDate,
		arg.DueDate,
		arg.GestationalAgeWeeks,
		arg.BirthWeight,
		arg.Apgar1,
		arg.Apgar2,
		arg.Premie,
		arg.BirthComplications,
		arg.Twin,
		arg.RaceEthnicity,
		arg.Languages,
		arg.RecruitmentSourceID,
		arg.RecruitmentSourceOther,
		arg.Response,
		arg.McdiPercentile,
		arg.McdiDate,
		arg.ID,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Sex,
		&i.BirthDate,
		&i.DueDate,
		&i.GestationalAgeWeeks,
		&i.BirthWeight,
		&i.Apgar1,
		&i.Apgar2,
		&i.Premie,
		&i.BirthComplications,
		&i.Twin,
		&i.RaceEthnicity,
		&i.Languages,
		&i.RecruitmentSourceID,
		&i.RecruitmentSourceOther,
		&i.Response,
		&i.CreatedByUserID,
		&i.DeactivatedAt,
		&i.InactiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.McdiPercentile,
		&i.McdiDate,
	)
	return i, err
}
