// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conditions.sql

package db

import (
	"context"
)

const createCondition = `-- name: CreateCondition :one
insert into conditions (lab_id, name) values ($1, $2)
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type CreateConditionParams struct {
	LabID int64  `json:"lab_id"`
	Name  string `json:"name"`
}

func (q *Queries) CreateCondition(ctx context.Context, arg CreateConditionParams) (Condition, error) {
	row := q.db.QueryRow(ctx, createCondition, arg.LabID, arg.Name)
	var i Condition
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConditionValue = `-- name: CreateConditionValue :one
insert into condition_values (condition_id, name) values ($1, $2)
returning id, condition_id, name, deactivated_at, created_at, updated_at
`

type CreateConditionValueParams struct {
	ConditionID int64  `json:"condition_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateConditionValue(ctx context.Context, arg CreateConditionValueParams) (ConditionValue, error) {
	row := q.db.QueryRow(ctx, createConditionValue, arg.ConditionID, arg.Name)
	var i ConditionValue
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCondition = `-- name: DeactivateCondition :exec
update conditions set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateCondition(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateCondition, id)
	return err
}

const deactivateConditionValue = `-- name: DeactivateConditionValue :exec
update condition_values set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateConditionValue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateConditionValue, id)
	return err
}

const getConditionByID = `-- name: GetConditionByID :one
select id, lab_id, name, deactivated_at, created_at, updated_at from conditions where id = $1
`

func (q *Queries) GetConditionByID(ctx context.Context, id int64) (Condition, error) {
	row := q.db.QueryRow(ctx, getConditionByID, id)
	var i Condition
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConditionValuesByCondition = `-- name: ListConditionValuesByCondition :many
select id, condition_id, name, deactivated_at, created_at, updated_at from condition_values where condition_id = $1 order by name
`

func (q *Queries) ListConditionValuesByCondition(ctx context.Context, conditionID int64) ([]ConditionValue, error) {
	rows, err := q.db.Query(ctx, listConditionValuesByCondition, conditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConditionValue
	for rows.Next() {
		var i ConditionValue
		if err := rows.Scan(
			&i.ID,
			&i.ConditionID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConditionsByLab = `-- name: ListConditionsByLab :many
select id, lab_id, name, deactivated_at, created_at, updated_at from conditions where lab_id = $1 order by name
`

func (q *Queries) ListConditionsByLab(ctx context.Context, labID int64) ([]Condition, error) {
	rows, err := q.db.Query(ctx, listConditionsByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Condition
	for rows.Next() {
		var i Condition
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCondition = `-- name: UpdateCondition :one
update conditions set name = $1 where id = $2
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type UpdateConditionParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCondition(ctx context.Context, arg UpdateConditionParams) (Condition, error) {
	row := q.db.QueryRow(ctx, updateCondition, arg.Name, arg.ID)
	var i Condition
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConditionValue = `-- name: UpdateConditionValue :one
update condition_values set name = $1 where id = $2
returning id, condition_id, name, deactivated_at, created_at, updated_at
`

type UpdateConditionValueParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateConditionValue(ctx context.Context, arg UpdateConditionValueParams) (ConditionValue, error) {
	row := q.db.QueryRow(ctx, updateConditionValue, arg.Name, arg.ID)
	var i ConditionValue
	err := row.Scan(
		&i.ID,
		&i.ConditionID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
