// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: equipment.sql

package db

import (
	"context"
)

const createEquipment = `-- name: CreateEquipment :one
insert into equipment (lab_id, name, quantity)
values ($1, $2, $3)
returning id, lab_id, name, quantity, deactivated_at, created_at, updated_at
`

type CreateEquipmentParams struct {
	LabID    int64  `json:"lab_id"`
	Name     string `json:"name"`
	Quantity int16  `json:"quantity"`
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, createEquipment, arg.LabID, arg.Name, arg.Quantity)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.Quantity,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateEquipment = `-- name: DeactivateEquipment :exec
update equipment set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateEquipment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateEquipment, id)
	return err
}

const getEquipmentByID = `-- name: GetEquipmentByID :one
select id, lab_id, name, quantity, deactivated_at, created_at, updated_at from equipment where id = $1
`

func (q *Queries) GetEquipmentByID(ctx context.Context, id int64) (Equipment, error) {
	row := q.db.QueryRow(ctx, getEquipmentByID, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.Quantity,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEquipmentByLab = `-- name: ListEquipmentByLab :many
select id, lab_id, name, quantity, deactivated_at, created_at, updated_at from equipment where lab_id = $1 order by name
`

func (q *Queries) ListEquipmentByLab(ctx context.Context, labID int64) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipmentByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.Quantity,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipment = `-- name: UpdateEquipment :one
update equipment set name = $1, quantity = $2
where id = $3
returning id, lab_id, name, quantity, deactivated_at, created_at, updated_at
`

type UpdateEquipmentParams struct {
	Name     string `json:"name"`
	Quantity int16  `json:"quantity"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, updateEquipment, arg.Name, arg.Quantity, arg.ID)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.Quantity,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
