// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package db

import (
	"context"
)

const createFamily = `-- name: CreateFamily :one
insert into families (address, city, state, zip, preferred_contact_method)
values (
    $1,
    $2,
    $3,
    $4,
    $5
)
returning id, address, city, state, zip, preferred_contact_method, created_at, updated_at
`

type CreateFamilyParams struct {
	Address                string  `json:"address"`
	City                   string  `json:"city"`
	State                  string  `json:"state"`
	Zip                    string  `json:"zip"`
	PreferredContactMethod *string `json:"preferred_contact_method"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.PreferredContactMethod,
	)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.PreferredContactMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamilyByID = `-- name: GetFamilyByID :one
select id, address, city, state, zip, preferred_contact_method, created_at, updated_at from families where id = $1
`

func (q *Queries) GetFamilyByID(ctx context.Context, id int64) (Family, error) {
	row := q.db.QueryRow(ctx, getFamilyByID, id)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.PreferredContactMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFamily = `-- name: UpdateFamily :one
update families set
    address = $1,
    city = $2,
    state = $3,
    zip = $4,
    preferred_contact_method = $5
where id = $6
returning id, address, city, state, zip, preferred_contact_method, created_at, updated_at
`

type UpdateFamilyParams struct {
	Address                string  `json:"address"`
	City                   string  `json:"city"`
	State                  string  `json:"state"`
	Zip                    string  `json:"zip"`
	PreferredContactMethod *string `json:"preferred_contact_method"`
	ID                     int64   `json:"id"`
}

func (q *Queries) UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, updateFamily,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.PreferredContactMethod,
		arg.ID,
	)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.PreferredContactMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
