// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package db

import (
	"context"
)

const createGrant = `-- name: CreateGrant :one
insert into grants (lab_id, name) values ($1, $2)
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type CreateGrantParams struct {
	LabID int64  `json:"lab_id"`
	Name  string `json:"name"`
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, createGrant, arg.LabID, arg.Name)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateGrant = `-- name: DeactivateGrant :exec
update grants set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateGrant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateGrant, id)
	return err
}

const getGrantByID = `-- name: GetGrantByID :one
select id, lab_id, name, deactivated_at, created_at, updated_at from grants where id = $1
`

func (q *Queries) GetGrantByID(ctx context.Context, id int64) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrantByID, id)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGrantsByLab = `-- name: ListGrantsByLab :many
select id, lab_id, name, deactivated_at, created_at, updated_at from grants where lab_id = $1 order by name
`

func (q *Queries) ListGrantsByLab(ctx context.Context, labID int64) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listGrantsByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grant
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrant = `-- name: UpdateGrant :one
update grants set name = $1 where id = $2
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type UpdateGrantParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateGrant(ctx context.Context, arg UpdateGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, updateGrant, arg.Name, arg.ID)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
