// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package db

import (
	"context"
)

const createGuardian = `-- name: CreateGuardian :one
insert into guardians (family_id, first_name, last_name, education, occupation, phone_number, phone_type, email)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning id, family_id, first_name, last_name, education, occupation, phone_number, phone_type, email, created_at, updated_at, deactivated_at
`

type CreateGuardianParams struct {
	FamilyID    int64   `json:"family_id"`
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	Education   string  `json:"education"`
	Occupation  string  `json:"occupation"`
	PhoneNumber string  `json:"phone_number"`
	PhoneType   *string `json:"phone_type"`
	Email       string  `json:"email"`
}

func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian,
		arg.FamilyID,
		arg.FirstName,
		arg.LastName,
		arg.Education,
		arg.Occupation,
		arg.PhoneNumber,
		arg.PhoneType,
		arg.Email,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Education,
		&i.Occupation,
		&i.PhoneNumber,
		&i.PhoneType,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const deactivateGuardian = `-- name: DeactivateGuardian :exec
update guardians set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateGuardian(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateGuardian, id)
	return err
}

const getGuardianByID = `-- name: GetGuardianByID :one
select id, family_id, first_name, last_name, education, occupation, phone_number, phone_type, email, created_at, updated_at, deactivated_at from guardians where id = $1
`

func (q *Queries) GetGuardianByID(ctx context.Context, id int64) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByID, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Education,
		&i.Occupation,
		&i.PhoneNumber,
		&i.PhoneType,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const listGuardiansByFamily = `-- name: ListGuardiansByFamily :many
select id, family_id, first_name, last_name, education, occupation, phone_number, phone_type, email, created_at, updated_at, deactivated_at from guardians where family_id = $1 order by id
`

func (q *Queries) ListGuardiansByFamily(ctx context.Context, familyID int64) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, listGuardiansByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guardian
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.FirstName,
			&i.LastName,
			&i.Education,
			&i.Occupation,
			&i.PhoneNumber,
			&i.PhoneType,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuardian = `-- name: UpdateGuardian :one
update guardians set
    first_name = $1,
    last_name = $2,
    education = $3,
    occupation = $4,
    phone_number = $5,
    phone_type = $6,
    email = $7
where id = $8
returning id, family_id, first_name, last_name, education, occupation, phone_number, phone_type, email, created_at, updated_at, deactivated_at
`

type UpdateGuardianParams struct {
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	Education   string  `json:"education"`
	Occupation  string  `json:"occupation"`
	PhoneNumber string  `json:"phone_number"`
	PhoneType   *string `json:"phone_type"`
	Email       string  `json:"email"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, updateGuardian,
		arg.FirstName,
		arg.LastName,
		arg.Education,
		arg.Occupation,
		arg.PhoneNumber,
		arg.PhoneType,
		arg.Email,
		arg.ID,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.LastName,
		&i.Education,
		&i.Occupation,
		&i.PhoneNumber,
		&i.PhoneType,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
