// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_memberships.sql

package db

import (
	"context"
)

const getLabMembership = `-- name: GetLabMembership :one
select id, user_id, lab_id, role_id, created_at, updated_at from lab_memberships where user_id = $1 and lab_id = $2
`

type GetLabMembershipParams struct {
	UserID int64 `json:"user_id"`
	LabID  int64 `json:"lab_id"`
}

func (q *Queries) GetLabMembership(ctx context.Context, arg GetLabMembershipParams) (LabMembership, error) {
	row := q.db.QueryRow(ctx, getLabMembership, arg.UserID, arg.LabID)
	var i LabMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabsForUser = `-- name: ListLabsForUser :many
select labs.id, labs.name, labs.short_name, labs.created_at, labs.updated_at from labs
join lab_memberships on lab_memberships.lab_id = labs.id
where lab_memberships.user_id = $1
order by labs.name
`

func (q *Queries) ListLabsForUser(ctx context.Context, userID int64) ([]Lab, error) {
	rows, err := q.db.Query(ctx, listLabsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lab
	for rows.Next() {
		var i Lab
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
