// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_member_trainings.sql

package db

import (
	"context"
)

const addLabMemberTraining = `-- name: AddLabMemberTraining :exec
insert into lab_member_trainings (user_id, experiment_role_id)
values ($1, $2)
`

type AddLabMemberTrainingParams struct {
	UserID           int64 `json:"user_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
}

func (q *Queries) AddLabMemberTraining(ctx context.Context, arg AddLabMemberTrainingParams) error {
	_, err := q.db.Exec(ctx, addLabMemberTraining, arg.UserID, arg.ExperimentRoleID)
	return err
}

const listLabMemberTrainingsForRole = `-- name: ListLabMemberTrainingsForRole :many
select users.id, users.email, users.first_name, users.last_name, users.password_hash, users.is_platform_admin, users.created_at, users.updated_at, users.deactivated_at from users
join lab_member_trainings on lab_member_trainings.user_id = users.id
where lab_member_trainings.experiment_role_id = $1
  and users.deactivated_at is null
order by users.id
`

// The trained-member pool for one experiment_role -- the candidate list
// the scheduling search's backtracking draws from for that role.
func (q *Queries) ListLabMemberTrainingsForRole(ctx context.Context, experimentRoleID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listLabMemberTrainingsForRole, experimentRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabMemberTrainingsForRoleByPriority = `-- name: ListLabMemberTrainingsForRoleByPriority :many
select users.id, users.email, users.first_name, users.last_name, users.password_hash, users.is_platform_admin, users.created_at, users.updated_at, users.deactivated_at from users
join lab_member_trainings on lab_member_trainings.user_id = users.id
left join lab_memberships
    on lab_memberships.user_id = users.id
    and lab_memberships.lab_id = $1
where lab_member_trainings.experiment_role_id = $2
  and users.deactivated_at is null
order by
    case lab_memberships.priority
        when 'undergrad_no_project' then 0
        when 'undergrad_with_project' then 1
        when 'lab_coordinator' then 2
        when 'graduate_student' then 3
        when 'postdoc' then 4
        when 'lab_director' then 5
        else 6
    end,
    users.id
`

type ListLabMemberTrainingsForRoleByPriorityParams struct {
	LabID            int64 `json:"lab_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
}

// Same candidate pool as ListLabMemberTrainingsForRole, but ordered by
// this lab's scheduling priority (lower priority scheduled first, e.g.
// undergrads before grad students) rather than plain user id --
// appointments_search.go uses this ordering directly as the
// scheduling.RoleCandidates candidate order, since FindAssignment
// fills each role from the front of its candidate list. left join, not
// join: a trained user missing a lab_memberships row for this lab
// (shouldn't happen, but isn't enforced by any FK) still comes back as
// a valid candidate -- just sorted last -- rather than silently
// vanishing from the candidate pool entirely.
func (q *Queries) ListLabMemberTrainingsForRoleByPriority(ctx context.Context, arg ListLabMemberTrainingsForRoleByPriorityParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listLabMemberTrainingsForRoleByPriority, arg.LabID, arg.ExperimentRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabMemberTrainingsForUser = `-- name: ListLabMemberTrainingsForUser :many
select experiment_roles.id, experiment_roles.lab_id, experiment_roles.name, experiment_roles.deactivated_at, experiment_roles.created_at, experiment_roles.updated_at, experiment_roles.is_sitter_role, experiment_roles.is_greeter_role from experiment_roles
join lab_member_trainings on lab_member_trainings.experiment_role_id = experiment_roles.id
where lab_member_trainings.user_id = $1
order by experiment_roles.id
`

func (q *Queries) ListLabMemberTrainingsForUser(ctx context.Context, userID int64) ([]ExperimentRole, error) {
	rows, err := q.db.Query(ctx, listLabMemberTrainingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExperimentRole
	for rows.Next() {
		var i ExperimentRole
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSitterRole,
			&i.IsGreeterRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabMemberTraining = `-- name: RemoveLabMemberTraining :exec
delete from lab_member_trainings
where user_id = $1 and experiment_role_id = $2
`

type RemoveLabMemberTrainingParams struct {
	UserID           int64 `json:"user_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
}

func (q *Queries) RemoveLabMemberTraining(ctx context.Context, arg RemoveLabMemberTrainingParams) error {
	_, err := q.db.Exec(ctx, removeLabMemberTraining, arg.UserID, arg.ExperimentRoleID)
	return err
}
