// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLabAvailabilityGeneral = `-- name: CreateLabAvailabilityGeneral :one
insert into lab_availability_general (user_id, lab_id, weekday, start_time, end_time)
values ($1, $2, $3, $4, $5)
returning id, user_id, lab_id, weekday, start_time, end_time, deactivated_at, created_at, updated_at
`

type CreateLabAvailabilityGeneralParams struct {
	UserID    int64       `json:"user_id"`
	LabID     int64       `json:"lab_id"`
	Weekday   int16       `json:"weekday"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateLabAvailabilityGeneral(ctx context.Context, arg CreateLabAvailabilityGeneralParams) (LabAvailabilityGeneral, error) {
	row := q.db.QueryRow(ctx, createLabAvailabilityGeneral,
		arg.UserID,
		arg.LabID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i LabAvailabilityGeneral
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLabAvailabilitySpecific = `-- name: CreateLabAvailabilitySpecific :one
insert into lab_availability_specific (user_id, lab_id, date, start_time, end_time)
values ($1, $2, $3, $4, $5)
returning id, user_id, lab_id, date, start_time, end_time, deactivated_at, created_at, updated_at
`

type CreateLabAvailabilitySpecificParams struct {
	UserID    int64       `json:"user_id"`
	LabID     int64       `json:"lab_id"`
	Date      pgtype.Date `json:"date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateLabAvailabilitySpecific(ctx context.Context, arg CreateLabAvailabilitySpecificParams) (LabAvailabilitySpecific, error) {
	row := q.db.QueryRow(ctx, createLabAvailabilitySpecific,
		arg.UserID,
		arg.LabID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var i LabAvailabilitySpecific
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateLabAvailabilityGeneral = `-- name: DeactivateLabAvailabilityGeneral :exec
update lab_availability_general set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateLabAvailabilityGeneral(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateLabAvailabilityGeneral, id)
	return err
}

const deactivateLabAvailabilitySpecific = `-- name: DeactivateLabAvailabilitySpecific :exec
update lab_availability_specific set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateLabAvailabilitySpecific(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateLabAvailabilitySpecific, id)
	return err
}

const getLabAvailabilityGeneralByID = `-- name: GetLabAvailabilityGeneralByID :one
select id, user_id, lab_id, weekday, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_general where id = $1
`

func (q *Queries) GetLabAvailabilityGeneralByID(ctx context.Context, id int64) (LabAvailabilityGeneral, error) {
	row := q.db.QueryRow(ctx, getLabAvailabilityGeneralByID, id)
	var i LabAvailabilityGeneral
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabAvailabilitySpecificByID = `-- name: GetLabAvailabilitySpecificByID :one
select id, user_id, lab_id, date, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_specific where id = $1
`

func (q *Queries) GetLabAvailabilitySpecificByID(ctx context.Context, id int64) (LabAvailabilitySpecific, error) {
	row := q.db.QueryRow(ctx, getLabAvailabilitySpecificByID, id)
	var i LabAvailabilitySpecific
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabAvailabilityGeneralByLab = `-- name: ListLabAvailabilityGeneralByLab :many
select id, user_id, lab_id, weekday, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_general
where lab_id = $1 and deactivated_at is null
`

// Every active member's general availability windows in a lab, for every
// weekday at once: general availability doesn't vary by date (it's a
// weekly-recurring schedule, not tied to any particular range), so a
// multi-day search needs this fetched only once, not once per candidate
// day -- the caller groups by weekday and filters to its candidate
// members in Go, and prefers a member's specific-date rows over these
// when both exist for the date in question.
func (q *Queries) ListLabAvailabilityGeneralByLab(ctx context.Context, labID int64) ([]LabAvailabilityGeneral, error) {
	rows, err := q.db.Query(ctx, listLabAvailabilityGeneralByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabAvailabilityGeneral
	for rows.Next() {
		var i LabAvailabilityGeneral
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LabID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabAvailabilityGeneralByUser = `-- name: ListLabAvailabilityGeneralByUser :many
select id, user_id, lab_id, weekday, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_general
where user_id = $1 and lab_id = $2 and deactivated_at is null
order by weekday, start_time
`

type ListLabAvailabilityGeneralByUserParams struct {
	UserID int64 `json:"user_id"`
	LabID  int64 `json:"lab_id"`
}

func (q *Queries) ListLabAvailabilityGeneralByUser(ctx context.Context, arg ListLabAvailabilityGeneralByUserParams) ([]LabAvailabilityGeneral, error) {
	rows, err := q.db.Query(ctx, listLabAvailabilityGeneralByUser, arg.UserID, arg.LabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabAvailabilityGeneral
	for rows.Next() {
		var i LabAvailabilityGeneral
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LabID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabAvailabilitySpecificByUser = `-- name: ListLabAvailabilitySpecificByUser :many
select id, user_id, lab_id, date, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_specific
where user_id = $1 and lab_id = $2 and deactivated_at is null
order by date, start_time
`

type ListLabAvailabilitySpecificByUserParams struct {
	UserID int64 `json:"user_id"`
	LabID  int64 `json:"lab_id"`
}

func (q *Queries) ListLabAvailabilitySpecificByUser(ctx context.Context, arg ListLabAvailabilitySpecificByUserParams) ([]LabAvailabilitySpecific, error) {
	rows, err := q.db.Query(ctx, listLabAvailabilitySpecificByUser, arg.UserID, arg.LabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabAvailabilitySpecific
	for rows.Next() {
		var i LabAvailabilitySpecific
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LabID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabAvailabilitySpecificForDateRange = `-- name: ListLabAvailabilitySpecificForDateRange :many
select id, user_id, lab_id, date, start_time, end_time, deactivated_at, created_at, updated_at from lab_availability_specific
where lab_id = $1
  and date between $2 and $3
  and deactivated_at is null
`

type ListLabAvailabilitySpecificForDateRangeParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// One query for a whole multi-day search range, rather than one call per
// candidate day -- the caller groups rows by date in Go.
func (q *Queries) ListLabAvailabilitySpecificForDateRange(ctx context.Context, arg ListLabAvailabilitySpecificForDateRangeParams) ([]LabAvailabilitySpecific, error) {
	rows, err := q.db.Query(ctx, listLabAvailabilitySpecificForDateRange, arg.LabID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabAvailabilitySpecific
	for rows.Next() {
		var i LabAvailabilitySpecific
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LabID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
