// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_memberships.sql

package db

import (
	"context"
)

const getLabMembership = `-- name: GetLabMembership :one
select id, user_id, lab_id, role_id, created_at, updated_at from lab_memberships where user_id = $1 and lab_id = $2
`

type GetLabMembershipParams struct {
	UserID int64 `json:"user_id"`
	LabID  int64 `json:"lab_id"`
}

func (q *Queries) GetLabMembership(ctx context.Context, arg GetLabMembershipParams) (LabMembership, error) {
	row := q.db.QueryRow(ctx, getLabMembership, arg.UserID, arg.LabID)
	var i LabMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
