// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_member_trainings.sql

package db

import (
	"context"
)

const addLabMemberTraining = `-- name: AddLabMemberTraining :exec
insert into lab_member_trainings (user_id, experiment_role_id)
values ($1, $2)
`

type AddLabMemberTrainingParams struct {
	UserID           int64 `json:"user_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
}

func (q *Queries) AddLabMemberTraining(ctx context.Context, arg AddLabMemberTrainingParams) error {
	_, err := q.db.Exec(ctx, addLabMemberTraining, arg.UserID, arg.ExperimentRoleID)
	return err
}

const listLabMemberTrainingsForRole = `-- name: ListLabMemberTrainingsForRole :many
select users.id, users.email, users.first_name, users.last_name, users.password_hash, users.is_platform_admin, users.created_at, users.updated_at, users.deactivated_at from users
join lab_member_trainings on lab_member_trainings.user_id = users.id
where lab_member_trainings.experiment_role_id = $1
  and users.deactivated_at is null
order by users.id
`

// The trained-member pool for one experiment_role -- the candidate list
// the scheduling search's backtracking draws from for that role.
func (q *Queries) ListLabMemberTrainingsForRole(ctx context.Context, experimentRoleID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listLabMemberTrainingsForRole, experimentRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabMemberTrainingsForUser = `-- name: ListLabMemberTrainingsForUser :many
select experiment_roles.id, experiment_roles.lab_id, experiment_roles.name, experiment_roles.deactivated_at, experiment_roles.created_at, experiment_roles.updated_at, experiment_roles.is_sitter_role from experiment_roles
join lab_member_trainings on lab_member_trainings.experiment_role_id = experiment_roles.id
where lab_member_trainings.user_id = $1
order by experiment_roles.id
`

func (q *Queries) ListLabMemberTrainingsForUser(ctx context.Context, userID int64) ([]ExperimentRole, error) {
	rows, err := q.db.Query(ctx, listLabMemberTrainingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExperimentRole
	for rows.Next() {
		var i ExperimentRole
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsSitterRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabMemberTraining = `-- name: RemoveLabMemberTraining :exec
delete from lab_member_trainings
where user_id = $1 and experiment_role_id = $2
`

type RemoveLabMemberTrainingParams struct {
	UserID           int64 `json:"user_id"`
	ExperimentRoleID int64 `json:"experiment_role_id"`
}

func (q *Queries) RemoveLabMemberTraining(ctx context.Context, arg RemoveLabMemberTrainingParams) error {
	_, err := q.db.Exec(ctx, removeLabMemberTraining, arg.UserID, arg.ExperimentRoleID)
	return err
}
