// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labs.sql

package db

import (
	"context"
)

const listLabs = `-- name: ListLabs :many
select id, name, short_name, created_at, updated_at from labs order by name
`

// Every lab in the system, regardless of membership -- unlike
// ListLabsForUser (lab_memberships.sql), this is for the
// platform-admin "assign a lab" picker, where the admin may not
// belong to the lab they're assigning someone else to. labs has no
// deactivated_at column, so there's nothing to filter out.
func (q *Queries) ListLabs(ctx context.Context) ([]Lab, error) {
	rows, err := q.db.Query(ctx, listLabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lab
	for rows.Next() {
		var i Lab
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
