// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEligibleChildrenForExperiment = `-- name: ListEligibleChildrenForExperiment :many
select children.id, children.family_id, children.first_name, children.last_name, children.sex, children.birth_date, children.due_date, children.gestational_age_weeks, children.birth_weight, children.apgar_1, children.apgar_2, children.premie, children.birth_complications, children.twin, children.race_ethnicity, children.languages, children.recruitment_source_id, children.recruitment_source_other, children.response, children.created_by_user_id, children.deactivated_at, children.inactive_reason, children.created_at, children.updated_at, children.mcdi_percentile, children.mcdi_date, children.birth_complications_notes
from children
join experiments on experiments.id = $1
where
    children.deactivated_at is null
    and children.birth_date is not null
    and children.birth_date >= $2::date - (experiments.age_range_max_months::float8 * interval '1 month')
    and children.birth_date <= $3::date - (experiments.age_range_min_months::float8 * interval '1 month')
    and (not experiments.filter_premies or coalesce(children.premie, false) = false)
    and (experiments.filter_min_languages = 0
         or coalesce(array_length(children.languages, 1), 0) >= experiments.filter_min_languages)
    and (cardinality(experiments.filter_languages) = 0
         or children.languages @> experiments.filter_languages)
    and ($4::text is null or children.sex = $4)
    and not exists (
        select 1 from appointments
        where appointments.child_id = children.id
          and appointments.status in ('to_be_scheduled', 'pending')
    )
`

type ListEligibleChildrenForExperimentParams struct {
	ExperimentID int64       `json:"experiment_id"`
	WindowStart  pgtype.Date `json:"window_start"`
	WindowEnd    pgtype.Date `json:"window_end"`
	Sex          *string     `json:"sex"`
}

// Every currently-active, not-already-held child eligible for a given
// experiment within a scheduling window [window_start, window_end]:
// their birth date must place their age inside the experiment's age
// range at *some* point in the window, not necessarily today. Mirrors
// legacy's hold-children formula: min_birth_date = window_start -
// max_age, max_birth_date = window_end - min_age -- the widest birth-date
// range for which some date in the window puts the child's age inside
// [min_age, max_age]. Age-range and filter columns come straight from
// the joined experiments row rather than being computed in Go first.
//
// "Held" is derived, not a stored flag: not exists a live
// (to_be_scheduled/pending) appointment for this child, for *any*
// experiment -- enforced elsewhere by appointments_one_active_hold_per_
// child, a partial unique index, not re-derived here as anything more
// than a filter.
//
// No ORDER BY/LIMIT: sort mode (oldest-first vs. random) and the
// requested count are applied by the caller in Go.
func (q *Queries) ListEligibleChildrenForExperiment(ctx context.Context, arg ListEligibleChildrenForExperimentParams) ([]Child, error) {
	rows, err := q.db.Query(ctx, listEligibleChildrenForExperiment,
		arg.ExperimentID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Sex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.FirstName,
			&i.LastName,
			&i.Sex,
			&i.BirthDate,
			&i.DueDate,
			&i.GestationalAgeWeeks,
			&i.BirthWeight,
			&i.Apgar1,
			&i.Apgar2,
			&i.Premie,
			&i.BirthComplications,
			&i.Twin,
			&i.RaceEthnicity,
			&i.Languages,
			&i.RecruitmentSourceID,
			&i.RecruitmentSourceOther,
			&i.Response,
			&i.CreatedByUserID,
			&i.DeactivatedAt,
			&i.InactiveReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.McdiPercentile,
			&i.McdiDate,
			&i.BirthComplicationsNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
