// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	ActorUserID *int64             `json:"actor_user_id"`
	LabID       *int64             `json:"lab_id"`
	Action      string             `json:"action"`
	EntityType  *string            `json:"entity_type"`
	EntityID    *int64             `json:"entity_id"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	Metadata    []byte             `json:"metadata"`
}

type Lab struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	ShortName string             `json:"short_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LabMembership struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	LabID     int64              `json:"lab_id"`
	RoleID    int64              `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         int64              `json:"id"`
	TokenHash  []byte             `json:"token_hash"`
	UserID     int64              `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID              int64              `json:"id"`
	Email           string             `json:"email"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	PasswordHash    *string            `json:"password_hash"`
	IsPlatformAdmin bool               `json:"is_platform_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt   pgtype.Timestamptz `json:"deactivated_at"`
}
