// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewsletter = `-- name: CreateNewsletter :one
insert into newsletters (lab_id, name) values ($1, $2)
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type CreateNewsletterParams struct {
	LabID int64  `json:"lab_id"`
	Name  string `json:"name"`
}

func (q *Queries) CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) (Newsletter, error) {
	row := q.db.QueryRow(ctx, createNewsletter, arg.LabID, arg.Name)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateNewsletter = `-- name: DeactivateNewsletter :exec
update newsletters set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateNewsletter(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateNewsletter, id)
	return err
}

const getNewsletterByID = `-- name: GetNewsletterByID :one
select id, lab_id, name, deactivated_at, created_at, updated_at from newsletters where id = $1
`

func (q *Queries) GetNewsletterByID(ctx context.Context, id int64) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getNewsletterByID, id)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEligibleFamiliesForNewsletter = `-- name: ListEligibleFamiliesForNewsletter :many
select distinct on (families.id)
    families.id as family_id,
    guardians.id as guardian_id,
    guardians.first_name,
    guardians.last_name,
    families.address,
    families.city,
    families.state,
    families.zip
from families
join children on children.family_id = families.id
join appointments on appointments.child_id = children.id
join experiments on experiments.id = appointments.experiment_id
join guardians on guardians.family_id = families.id
where experiments.lab_id = $1
  and appointments.status = 'arrived'
  and appointments.schedule_date between $2 and $3
  and ($4::bigint is null or not exists (
      select 1 from newsletters_parents
      where newsletters_parents.newsletter_id = $4
        and newsletters_parents.guardian_id = guardians.id
  ))
order by families.id, guardians.id
`

type ListEligibleFamiliesForNewsletterParams struct {
	LabID        int64       `json:"lab_id"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	NewsletterID *int64      `json:"newsletter_id"`
}

type ListEligibleFamiliesForNewsletterRow struct {
	FamilyID   int64  `json:"family_id"`
	GuardianID int64  `json:"guardian_id"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	Address    string `json:"address"`
	City       string `json:"city"`
	State      string `json:"state"`
	Zip        string `json:"zip"`
}

// One row per family with an 'arrived' appointment for this lab in the
// window, represented by its lowest-id guardian (matching legacy's
// single-guardian-per-row mail-merge shape). When newsletter_id is
// given, excludes a (family, guardian) pairing already marked sent for
// that newsletter -- note this can fall through to a different
// (higher-id) guardian in the same family if the lowest-id one already
// received it, rather than dropping the family outright.
func (q *Queries) ListEligibleFamiliesForNewsletter(ctx context.Context, arg ListEligibleFamiliesForNewsletterParams) ([]ListEligibleFamiliesForNewsletterRow, error) {
	rows, err := q.db.Query(ctx, listEligibleFamiliesForNewsletter,
		arg.LabID,
		arg.StartDate,
		arg.EndDate,
		arg.NewsletterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleFamiliesForNewsletterRow
	for rows.Next() {
		var i ListEligibleFamiliesForNewsletterRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.GuardianID,
			&i.FirstName,
			&i.LastName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewslettersByLab = `-- name: ListNewslettersByLab :many
select id, lab_id, name, deactivated_at, created_at, updated_at from newsletters where lab_id = $1 order by name
`

func (q *Queries) ListNewslettersByLab(ctx context.Context, labID int64) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, listNewslettersByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Newsletter
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNewsletterSent = `-- name: MarkNewsletterSent :exec
insert into newsletters_parents (newsletter_id, guardian_id)
values ($1, $2)
on conflict do nothing
`

type MarkNewsletterSentParams struct {
	NewsletterID int64 `json:"newsletter_id"`
	GuardianID   int64 `json:"guardian_id"`
}

func (q *Queries) MarkNewsletterSent(ctx context.Context, arg MarkNewsletterSentParams) error {
	_, err := q.db.Exec(ctx, markNewsletterSent, arg.NewsletterID, arg.GuardianID)
	return err
}
