// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
insert into notes (entity_type, entity_id, author_user_id, body)
values (
    $1,
    $2,
    $3,
    $4
)
returning id, entity_type, entity_id, author_user_id, body, created_at
`

type CreateNoteParams struct {
	EntityType   string `json:"entity_type"`
	EntityID     int64  `json:"entity_id"`
	AuthorUserID int64  `json:"author_user_id"`
	Body         string `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.EntityType,
		arg.EntityID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesByEntity = `-- name: ListNotesByEntity :many
select id, entity_type, entity_id, author_user_id, body, created_at from notes
where entity_type = $1 and entity_id = $2
order by created_at
`

type ListNotesByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
