// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_set_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPasswordSetToken = `-- name: ClaimPasswordSetToken :one
update password_set_tokens
set used_at = now()
where token_hash = $1 and used_at is null and expires_at > now()
returning id, token_hash, user_id, created_at, expires_at, used_at
`

// Atomically checks and consumes a token in one statement: the WHERE
// clause and the used_at write happen under the same row lock, so two
// concurrent redemptions of the same token can't both observe
// used_at is null and both proceed -- the second one's WHERE clause
// simply no longer matches once the first commits, returning no rows.
// A separate SELECT-then-UPDATE (checking used_at, then writing it in a
// later statement) would leave a window for exactly that race.
func (q *Queries) ClaimPasswordSetToken(ctx context.Context, tokenHash []byte) (PasswordSetToken, error) {
	row := q.db.QueryRow(ctx, claimPasswordSetToken, tokenHash)
	var i PasswordSetToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordSetToken = `-- name: CreatePasswordSetToken :one
insert into password_set_tokens (token_hash, user_id, expires_at)
values ($1, $2, $3)
returning id, token_hash, user_id, created_at, expires_at, used_at
`

type CreatePasswordSetTokenParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordSetToken(ctx context.Context, arg CreatePasswordSetTokenParams) (PasswordSetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordSetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i PasswordSetToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
