// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: protocols.sql

package db

import (
	"context"
)

const createProtocol = `-- name: CreateProtocol :one
insert into protocols (lab_id, name) values ($1, $2)
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type CreateProtocolParams struct {
	LabID int64  `json:"lab_id"`
	Name  string `json:"name"`
}

func (q *Queries) CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error) {
	row := q.db.QueryRow(ctx, createProtocol, arg.LabID, arg.Name)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProtocol = `-- name: DeactivateProtocol :exec
update protocols set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateProtocol(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateProtocol, id)
	return err
}

const getProtocolByID = `-- name: GetProtocolByID :one
select id, lab_id, name, deactivated_at, created_at, updated_at from protocols where id = $1
`

func (q *Queries) GetProtocolByID(ctx context.Context, id int64) (Protocol, error) {
	row := q.db.QueryRow(ctx, getProtocolByID, id)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProtocolsByLab = `-- name: ListProtocolsByLab :many
select id, lab_id, name, deactivated_at, created_at, updated_at from protocols where lab_id = $1 order by name
`

func (q *Queries) ListProtocolsByLab(ctx context.Context, labID int64) ([]Protocol, error) {
	rows, err := q.db.Query(ctx, listProtocolsByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Protocol
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Name,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProtocol = `-- name: UpdateProtocol :one
update protocols set name = $1 where id = $2
returning id, lab_id, name, deactivated_at, created_at, updated_at
`

type UpdateProtocolParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateProtocol(ctx context.Context, arg UpdateProtocolParams) (Protocol, error) {
	row := q.db.QueryRow(ctx, updateProtocol, arg.Name, arg.ID)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Name,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
