// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateChild(ctx context.Context, arg CreateChildParams) (Child, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error)
	CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateRecruitmentSource(ctx context.Context, name string) (RecruitmentSource, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateChild(ctx context.Context, arg DeactivateChildParams) error
	DeleteGuardian(ctx context.Context, id int64) error
	GetChildByID(ctx context.Context, id int64) (Child, error)
	GetFamilyByID(ctx context.Context, id int64) (Family, error)
	GetGuardianByID(ctx context.Context, id int64) (Guardian, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListActiveRecruitmentSources(ctx context.Context) ([]RecruitmentSource, error)
	ListChildrenByFamily(ctx context.Context, familyID int64) ([]Child, error)
	ListGuardiansByFamily(ctx context.Context, familyID int64) ([]Guardian, error)
	ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error)
	RevokeSession(ctx context.Context, tokenHash []byte) error
	// Every filter is optional (sqlc.narg(x) is null or ...); passing none
	// returns every child (subject to include_deactivated/limit_count).
	//
	// Name matching uses pg_trgm's word_similarity rather than plain
	// similarity() or ILIKE: word_similarity scores how well the query matches
	// *part of* the field, so a short query like "jhon" can still match
	// "Johnathan" -- plain similarity() compares the whole strings and craters
	// when they're very different lengths, and ILIKE only catches exact
	// substrings, not typos. The 0.2 threshold is a literal in the query
	// rather than the pg_trgm.similarity_threshold GUC (the %/<% operators'
	// default is 0.3, too strict for short name fields, and overriding a GUC
	// per-query risks leaking to the next query on a pooled connection).
	SearchChildren(ctx context.Context, arg SearchChildrenParams) ([]Child, error)
	// Existing-family lookup, primarily to catch duplicates before creating a
	// new family record for what's actually an existing one -- the legacy app
	// had this exact problem badly enough to need three separate hand-run
	// merge/dedupe SQL scripts. Matches if any guardian on the family matches
	// the name/email/phone filters, or the family's own address fields match.
	// A family with no guardians yet can't match on guardian filters (inner
	// join); that's fine since a family is always created together with its
	// first guardian in normal use.
	//
	// Results are ordered by id rather than name-match quality: DISTINCT
	// requires ORDER BY expressions to be in the select list, and this is a
	// "review a handful of candidates" tool for staff, not a ranked search --
	// ranking isn't worth the extra query complexity here.
	SearchFamilies(ctx context.Context, arg SearchFamiliesParams) ([]Family, error)
	TouchSessionLastSeen(ctx context.Context, id int64) error
	UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error)
	UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error)
	UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error)
}

var _ Querier = (*Queries)(nil)
