// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Join management: conditions, equipment, and training-role requirements
	// for an experiment. Each List query joins back to the lookup table so
	// callers get full rows (name, etc.) in one query instead of N+1 lookups.
	//
	// Each Add* query below is an insert...select gated on an exists check
	// that the target row belongs to the same lab as the experiment --
	// request authorization (requireLabMemberForExperiment) only checks the
	// experiment's own lab, not whether the attached id belongs to it, so
	// without this a lab member could attach another lab's condition/
	// equipment/role/grant/user by guessing its id. :execrows lets the
	// handler tell "attached" (1 row) apart from "cross-lab or unknown id"
	// (0 rows, since the insert then has nothing to select) without a
	// separate existence query.
	AddExperimentCondition(ctx context.Context, arg AddExperimentConditionParams) (int64, error)
	AddExperimentEquipment(ctx context.Context, arg AddExperimentEquipmentParams) (int64, error)
	AddExperimentGrant(ctx context.Context, arg AddExperimentGrantParams) (int64, error)
	AddExperimentPrincipalInvestigator(ctx context.Context, arg AddExperimentPrincipalInvestigatorParams) (int64, error)
	AddExperimentTrainingRequirement(ctx context.Context, arg AddExperimentTrainingRequirementParams) (int64, error)
	AddLabMemberTraining(ctx context.Context, arg AddLabMemberTrainingParams) error
	// Only a scheduled ('pending') appointment can arrive -- an unscheduled
	// one has no date/time for a visit to have happened at. Frees the hold,
	// same as ReleaseAppointment, since 'arrived' also falls outside
	// appointments_one_active_hold_per_child's predicate.
	ArriveAppointment(ctx context.Context, id int64) (Appointment, error)
	// Atomically checks and consumes a token in one statement: the WHERE
	// clause and the used_at write happen under the same row lock, so two
	// concurrent redemptions of the same token can't both observe
	// used_at is null and both proceed -- the second one's WHERE clause
	// simply no longer matches once the first commits, returning no rows.
	// A separate SELECT-then-UPDATE (checking used_at, then writing it in a
	// later statement) would leave a window for exactly that race.
	ClaimPasswordSetToken(ctx context.Context, tokenHash []byte) (PasswordSetToken, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentExperimenter(ctx context.Context, arg CreateAppointmentExperimenterParams) (AppointmentExperimenter, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateChild(ctx context.Context, arg CreateChildParams) (Child, error)
	CreateCondition(ctx context.Context, arg CreateConditionParams) (Condition, error)
	CreateConditionValue(ctx context.Context, arg CreateConditionValueParams) (ConditionValue, error)
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error)
	CreateExperiment(ctx context.Context, arg CreateExperimentParams) (Experiment, error)
	CreateExperimentRole(ctx context.Context, arg CreateExperimentRoleParams) (ExperimentRole, error)
	CreateExperimentType(ctx context.Context, arg CreateExperimentTypeParams) (ExperimentType, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error)
	CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error)
	CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error)
	CreateLabAvailabilityGeneral(ctx context.Context, arg CreateLabAvailabilityGeneralParams) (LabAvailabilityGeneral, error)
	CreateLabAvailabilitySpecific(ctx context.Context, arg CreateLabAvailabilitySpecificParams) (LabAvailabilitySpecific, error)
	// priority is deliberately omitted -- the column's own default
	// ('undergrad_no_project') applies, tuned afterward via
	// UpdateLabMembership. The table's unique(user_id, lab_id) constraint
	// rejects adding someone already a member (surfaces as a 409 via the
	// existing writeDBError conflict handling).
	CreateLabMembership(ctx context.Context, arg CreateLabMembershipParams) (LabMembership, error)
	CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) (Newsletter, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreatePasswordSetToken(ctx context.Context, arg CreatePasswordSetTokenParams) (PasswordSetToken, error)
	CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error)
	CreateRecruitmentSource(ctx context.Context, name string) (RecruitmentSource, error)
	CreateScheduleBlocking(ctx context.Context, arg CreateScheduleBlockingParams) (ScheduleBlocking, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateZipCode(ctx context.Context, arg CreateZipCodeParams) (Zipcode, error)
	DeactivateChild(ctx context.Context, arg DeactivateChildParams) error
	DeactivateCondition(ctx context.Context, id int64) error
	DeactivateConditionValue(ctx context.Context, id int64) error
	DeactivateEquipment(ctx context.Context, id int64) error
	DeactivateExperiment(ctx context.Context, id int64) error
	// Also clears is_sitter_role/is_greeter_role: a deactivated role retiring
	// from the lab's normal training-requirement machinery should retire
	// from these designations too, rather than leaving a dangling "this
	// retired role is still the lab's sitter/greeter" state that only a raw
	// DB query would reveal (GetSitterRoleForLab/GetGreeterRoleForLab below
	// also filter deactivated_at as defense in depth, but a lab should never
	// end up needing that filter to matter).
	DeactivateExperimentRole(ctx context.Context, id int64) error
	DeactivateExperimentType(ctx context.Context, id int64) error
	DeactivateGrant(ctx context.Context, id int64) error
	DeactivateGuardian(ctx context.Context, id int64) error
	DeactivateLabAvailabilityGeneral(ctx context.Context, id int64) error
	DeactivateLabAvailabilitySpecific(ctx context.Context, id int64) error
	DeactivateNewsletter(ctx context.Context, id int64) error
	DeactivateProtocol(ctx context.Context, id int64) error
	DeactivateScheduleBlocking(ctx context.Context, id int64) error
	// :one (RETURNING), not :exec, so deactivating a nonexistent id 404s
	// instead of silently reporting success -- same reasoning as
	// RemoveLabMembership.
	DeactivateUser(ctx context.Context, id int64) (User, error)
	DeactivateZipCode(ctx context.Context, id int64) error
	// Per-child listing of 'arrived' appointments for one experiment in a
	// date range, with age at the appointment (in months) and the family's
	// first (lowest-id) guardian's education level. Handler computes summary
	// counts over these rows in Go rather than a second query.
	DemographicsReport(ctx context.Context, arg DemographicsReportParams) ([]DemographicsReportRow, error)
	GetAppointmentByID(ctx context.Context, id int64) (Appointment, error)
	// For lab-membership authorization (mirrors GetConditionValueLabID):
	// appointments has no lab_id of its own, so resolve it via the experiment.
	GetAppointmentLabID(ctx context.Context, id int64) (int64, error)
	GetChildByID(ctx context.Context, id int64) (Child, error)
	GetConditionByID(ctx context.Context, id int64) (Condition, error)
	// Resolves the lab a condition_value belongs to via its parent condition,
	// for lab-membership authorization -- condition_values has no lab_id of
	// its own.
	GetConditionValueLabID(ctx context.Context, id int64) (int64, error)
	GetEquipmentByID(ctx context.Context, id int64) (Equipment, error)
	GetExperimentByID(ctx context.Context, id int64) (Experiment, error)
	GetExperimentRoleByID(ctx context.Context, id int64) (ExperimentRole, error)
	GetExperimentTypeByID(ctx context.Context, id int64) (ExperimentType, error)
	GetFamilyByID(ctx context.Context, id int64) (Family, error)
	GetGrantByID(ctx context.Context, id int64) (Grant, error)
	GetGreeterRoleForLab(ctx context.Context, labID int64) (ExperimentRole, error)
	GetGuardianByID(ctx context.Context, id int64) (Guardian, error)
	GetJobLastRun(ctx context.Context, jobName string) (pgtype.Timestamptz, error)
	GetLabAvailabilityGeneralByID(ctx context.Context, id int64) (LabAvailabilityGeneral, error)
	GetLabAvailabilitySpecificByID(ctx context.Context, id int64) (LabAvailabilitySpecific, error)
	GetLabMembership(ctx context.Context, arg GetLabMembershipParams) (LabMembership, error)
	GetNewsletterByID(ctx context.Context, id int64) (Newsletter, error)
	GetProtocolByID(ctx context.Context, id int64) (Protocol, error)
	GetScheduleBlockingByID(ctx context.Context, id int64) (ScheduleBlocking, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetSitterRoleForLab(ctx context.Context, labID int64) (ExperimentRole, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserBySSOIdentity(ctx context.Context, arg GetUserBySSOIdentityParams) (User, error)
	GetZipCodeByID(ctx context.Context, id int64) (Zipcode, error)
	// Distinct-child 'arrived' counts per protocol in a date range, for the
	// lab's Human Research Committee (IRB) reporting.
	HRCReportByProtocol(ctx context.Context, arg HRCReportByProtocolParams) ([]HRCReportByProtocolRow, error)
	// All-protocols total for the same window, lab-wide (including
	// experiments with no protocol assigned).
	HRCReportTotal(ctx context.Context, arg HRCReportTotalParams) (int64, error)
	// Backs requireLabAdminFromURL: unlike plain lab membership (checked by
	// GetLabMembership), managing OTHER members -- creating, editing their
	// permission role and priority, or removing them -- requires the caller
	// to hold this lab's "admin" role, not just any membership.
	IsLabAdmin(ctx context.Context, arg IsLabAdminParams) (bool, error)
	ListActiveRecruitmentSources(ctx context.Context) ([]RecruitmentSource, error)
	// Joined to users/experiment_roles for display -- a scheduled
	// appointment's staff assignment is shown by name and role, not id.
	ListAppointmentExperimenters(ctx context.Context, appointmentID int64) ([]ListAppointmentExperimentersRow, error)
	// A child's own appointment history across every experiment, excluding
	// still-unscheduled holds -- shown on the hold-selection screen as
	// "Previous Studies" (legacy's child-id->experiments).
	ListAppointmentsByChild(ctx context.Context, childID int64) ([]ListAppointmentsByChildRow, error)
	ListAppointmentsByExperiment(ctx context.Context, arg ListAppointmentsByExperimentParams) ([]Appointment, error)
	// Same as ListAppointmentsByChild, for the child's siblings (other
	// children sharing its family_id) -- legacy's
	// child-id->sibling-experiments.
	ListAppointmentsBySiblings(ctx context.Context, childID int64) ([]ListAppointmentsBySiblingsRow, error)
	// Pending, not-yet-reminded appointments starting at or before the given
	// cutoff (now + lead time), with the family's representative (lowest-id)
	// guardian -- same idiom ListEligibleFamiliesForNewsletter uses. A
	// family with no guardians at all (guardian_email null) is left for the
	// caller to skip and log, not silently dropped here.
	ListAppointmentsDueForReminder(ctx context.Context, dueBefore pgtype.Timestamp) ([]ListAppointmentsDueForReminderRow, error)
	// Members already committed to a Pending appointment within this date
	// range in this lab, with the date and time range they're busy -- one
	// query for a whole multi-day search rather than one call per candidate
	// day; the caller groups rows by date in Go.
	ListBusyAppointmentExperimentersForDateRange(ctx context.Context, arg ListBusyAppointmentExperimentersForDateRangeParams) ([]ListBusyAppointmentExperimentersForDateRangeRow, error)
	// Equipment already required by a Pending appointment within this date
	// range in this lab, with the date and time range it's in use -- counted
	// against each equipment's quantity for that day's availability grid.
	ListBusyEquipmentForDateRange(ctx context.Context, arg ListBusyEquipmentForDateRangeParams) ([]ListBusyEquipmentForDateRangeRow, error)
	// Distinct appointment IDs with a relevant audit event since the digest's
	// last run -- replaces legacy's change_status dirty-flag column with a
	// query over the audit log this project already maintains as a hard
	// requirement. entity_id is forced non-null via coalesce (safe: the
	// where clause already excludes null entity_id) so the Go side gets a
	// plain int64, not a pointer.
	ListChangedAppointmentIDsSince(ctx context.Context, arg ListChangedAppointmentIDsSinceParams) ([]int64, error)
	ListChildrenByFamily(ctx context.Context, familyID int64) ([]Child, error)
	ListConditionValuesByCondition(ctx context.Context, conditionID int64) ([]ConditionValue, error)
	ListConditionsByLab(ctx context.Context, labID int64) ([]Condition, error)
	// Every currently-active, not-already-held child eligible for a given
	// experiment within a scheduling window [window_start, window_end]:
	// their birth date must place their age inside the experiment's age
	// range at *some* point in the window, not necessarily today. Mirrors
	// legacy's hold-children formula: min_birth_date = window_start -
	// max_age, max_birth_date = window_end - min_age -- the widest birth-date
	// range for which some date in the window puts the child's age inside
	// [min_age, max_age]. Age-range and filter columns come straight from
	// the joined experiments row rather than being computed in Go first.
	//
	// "Held" is derived, not a stored flag: not exists a live
	// (to_be_scheduled/pending) appointment for this child, for *any*
	// experiment -- enforced elsewhere by appointments_one_active_hold_per_
	// child, a partial unique index, not re-derived here as anything more
	// than a filter.
	//
	// No ORDER BY/LIMIT: sort mode (oldest-first vs. random) and the
	// requested count are applied by the caller in Go.
	ListEligibleChildrenForExperiment(ctx context.Context, arg ListEligibleChildrenForExperimentParams) ([]Child, error)
	// One row per family with an 'arrived' appointment for this lab in the
	// window, represented by its lowest-id guardian (matching legacy's
	// single-guardian-per-row mail-merge shape). When newsletter_id is
	// given, excludes a (family, guardian) pairing already marked sent for
	// that newsletter -- note this can fall through to a different
	// (higher-id) guardian in the same family if the lowest-id one already
	// received it, rather than dropping the family outright.
	ListEligibleFamiliesForNewsletter(ctx context.Context, arg ListEligibleFamiliesForNewsletterParams) ([]ListEligibleFamiliesForNewsletterRow, error)
	ListEquipmentByLab(ctx context.Context, labID int64) ([]Equipment, error)
	ListExperimentConditions(ctx context.Context, experimentID int64) ([]Condition, error)
	ListExperimentEquipment(ctx context.Context, experimentID int64) ([]Equipment, error)
	ListExperimentGrants(ctx context.Context, experimentID int64) ([]Grant, error)
	ListExperimentPrincipalInvestigators(ctx context.Context, experimentID int64) ([]User, error)
	ListExperimentRolesByLab(ctx context.Context, labID int64) ([]ExperimentRole, error)
	ListExperimentTrainingRequirements(ctx context.Context, experimentID int64) ([]ExperimentRole, error)
	ListExperimentTypesByLab(ctx context.Context, labID int64) ([]ExperimentType, error)
	ListExperimentsByLab(ctx context.Context, labID int64) ([]Experiment, error)
	ListGrantsByLab(ctx context.Context, labID int64) ([]Grant, error)
	ListGuardiansByFamily(ctx context.Context, familyID int64) ([]Guardian, error)
	// Every active member's general availability windows in a lab, for every
	// weekday at once: general availability doesn't vary by date (it's a
	// weekly-recurring schedule, not tied to any particular range), so a
	// multi-day search needs this fetched only once, not once per candidate
	// day -- the caller groups by weekday and filters to its candidate
	// members in Go, and prefers a member's specific-date rows over these
	// when both exist for the date in question.
	ListLabAvailabilityGeneralByLab(ctx context.Context, labID int64) ([]LabAvailabilityGeneral, error)
	ListLabAvailabilityGeneralByUser(ctx context.Context, arg ListLabAvailabilityGeneralByUserParams) ([]LabAvailabilityGeneral, error)
	ListLabAvailabilitySpecificByUser(ctx context.Context, arg ListLabAvailabilitySpecificByUserParams) ([]LabAvailabilitySpecific, error)
	// One query for a whole multi-day search range, rather than one call per
	// candidate day -- the caller groups rows by date in Go.
	ListLabAvailabilitySpecificForDateRange(ctx context.Context, arg ListLabAvailabilitySpecificForDateRangeParams) ([]LabAvailabilitySpecific, error)
	// The trained-member pool for one experiment_role -- the candidate list
	// the scheduling search's backtracking draws from for that role.
	ListLabMemberTrainingsForRole(ctx context.Context, experimentRoleID int64) ([]User, error)
	// Same candidate pool as ListLabMemberTrainingsForRole, but ordered by
	// this lab's scheduling priority (lower priority scheduled first, e.g.
	// undergrads before grad students) rather than plain user id --
	// appointments_search.go uses this ordering directly as the
	// scheduling.RoleCandidates candidate order, since FindAssignment
	// fills each role from the front of its candidate list. left join, not
	// join: a trained user missing a lab_memberships row for this lab
	// (shouldn't happen, but isn't enforced by any FK) still comes back as
	// a valid candidate -- just sorted last -- rather than silently
	// vanishing from the candidate pool entirely.
	ListLabMemberTrainingsForRoleByPriority(ctx context.Context, arg ListLabMemberTrainingsForRoleByPriorityParams) ([]User, error)
	// Scoped to one lab: a user's trainings for OTHER labs aren't that
	// lab's business, and the lab-members admin page (the only caller) only
	// ever wants "what is this member trained for here". The handler also
	// confirms {userID} is actually a member of {labID} before calling this
	// -- otherwise a member of lab A could request another lab's member's
	// trainings just by naming their user id.
	ListLabMemberTrainingsForUser(ctx context.Context, arg ListLabMemberTrainingsForUserParams) ([]ExperimentRole, error)
	// The candidate pool a picker (e.g. principal investigators) draws
	// from -- full User rows, same "select users.*, filter deactivated"
	// shape as ListLabMemberTrainingsForRole.
	ListLabMembers(ctx context.Context, labID int64) ([]User, error)
	// The lab-members admin page's roster: membership details (permission
	// role, scheduling priority), not just the bare user rows ListLabMembers
	// (a different, existing query used by several AttachList pickers)
	// returns -- that one's response shape is relied on elsewhere and
	// shouldn't change.
	ListLabMembershipsForLab(ctx context.Context, labID int64) ([]ListLabMembershipsForLabRow, error)
	// Every lab in the system, regardless of membership -- unlike
	// ListLabsForUser (lab_memberships.sql), this is for the
	// platform-admin "assign a lab" picker, where the admin may not
	// belong to the lab they're assigning someone else to. labs has no
	// deactivated_at column, so there's nothing to filter out.
	ListLabs(ctx context.Context) ([]Lab, error)
	ListLabsForUser(ctx context.Context, userID int64) ([]Lab, error)
	ListNewslettersByLab(ctx context.Context, labID int64) ([]Newsletter, error)
	ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error)
	// One recipient's current upcoming Pending schedule in one lab -- the
	// digest email body. Filters to appointments the given user is assigned
	// to (via exists), but aggregates role names across every experimenter
	// on the appointment, not just the recipient's own role, matching
	// legacy's "(roles)" showing the whole assigned team for context.
	ListPendingAppointmentsForUserInLab(ctx context.Context, arg ListPendingAppointmentsForUserInLabParams) ([]ListPendingAppointmentsForUserInLabRow, error)
	ListProtocolsByLab(ctx context.Context, labID int64) ([]Protocol, error)
	// Distinct (staff member, lab) pairs assigned to any of the given
	// appointments -- the digest's recipients. Recipients come from
	// appointment_experimenters (who's actually assigned), not from the
	// audit event's actor (who might be an admin scheduling on someone
	// else's behalf).
	ListRecipientsForAppointments(ctx context.Context, appointmentIds []int64) ([]ListRecipientsForAppointmentsRow, error)
	// The fixed, small set of permission-level roles (staff/coordinator/
	// admin) a lab membership can be assigned -- not lab-scoped, and not
	// editable from the lab-members admin page (see lab_memberships.sql).
	ListRoles(ctx context.Context) ([]Role, error)
	ListScheduleBlockingsByLab(ctx context.Context, labID int64) ([]ScheduleBlocking, error)
	// One query for a whole multi-day search range, rather than one call per
	// candidate day -- the caller groups rows by date in Go.
	ListScheduleBlockingsForDateRange(ctx context.Context, arg ListScheduleBlockingsForDateRangeParams) ([]ScheduleBlocking, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListZipCodesByLab(ctx context.Context, labID int64) ([]Zipcode, error)
	MarkAppointmentReminderSent(ctx context.Context, id int64) error
	MarkNewsletterSent(ctx context.Context, arg MarkNewsletterSentParams) error
	// One row per distinct child with an 'arrived' appointment in range --
	// the current-shape NIH participant-level data template, which must be
	// submitted as a flat CSV (one row per participant) rather than the
	// old aggregate category/sex crosstab. Race/ethnicity/sex label
	// mapping and age-unit computation happen in Go (see nih_report.go),
	// not here, so a null birth_date can be handled explicitly rather than
	// relying on sqlc's nullability inference over a computed expression.
	// When a child has more than one qualifying appointment in the window,
	// the earliest one is used for age-at-visit (distinct on + order by
	// schedule_date), matching the distinct-child counting the old
	// aggregate queries already used.
	NIHParticipantReport(ctx context.Context, arg NIHParticipantReportParams) ([]NIHParticipantReportRow, error)
	// Deliberately allows releasing a 'pending' (already time-scheduled)
	// appointment, not just an unscheduled one -- matches legacy's per-child
	// release, which does the same. Frees the child up again: 'released'
	// falls outside appointments_one_active_hold_per_child's predicate.
	ReleaseAppointment(ctx context.Context, id int64) (Appointment, error)
	RemoveExperimentCondition(ctx context.Context, arg RemoveExperimentConditionParams) error
	RemoveExperimentEquipment(ctx context.Context, arg RemoveExperimentEquipmentParams) error
	RemoveExperimentGrant(ctx context.Context, arg RemoveExperimentGrantParams) error
	RemoveExperimentPrincipalInvestigator(ctx context.Context, arg RemoveExperimentPrincipalInvestigatorParams) error
	RemoveExperimentTrainingRequirement(ctx context.Context, arg RemoveExperimentTrainingRequirementParams) error
	RemoveLabMemberTraining(ctx context.Context, arg RemoveLabMemberTrainingParams) error
	// Run alongside RemoveLabMembership, in the same transaction: removing
	// someone from a lab should also retire them from that lab's studies,
	// not leave their trainings behind as a dangling, still-schedulable
	// candidate (see ListLabMemberTrainingsForRoleByPriority's LEFT JOIN,
	// which tolerates a trained user with no lab_memberships row for
	// legacy-import reasons -- that tolerance was never meant to cover a
	// live "remove this person" action producing the same shape on
	// purpose).
	RemoveLabMemberTrainingsForUserInLab(ctx context.Context, arg RemoveLabMemberTrainingsForUserInLabParams) error
	// A hard delete, not a deactivation -- lab_memberships has no
	// deactivated_at column. Returns the removed row (rather than :exec) so
	// the caller can 404 when nothing matched, and use the real
	// lab_memberships.id for its audit event -- consistent with
	// Create/UpdateLabMembership, which both use the actual row id, not the
	// user id.
	RemoveLabMembership(ctx context.Context, arg RemoveLabMembershipParams) (LabMembership, error)
	// Deactivating a user must end their access immediately, not just block
	// future logins -- without this, a session issued before deactivation
	// would keep working until it naturally expires (up to sessionTTL, 7
	// days).
	RevokeAllSessionsForUser(ctx context.Context, userID int64) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
	// Commits a chosen slot: the caller re-validates availability itself
	// immediately before calling this (defensive re-check against staleness,
	// since time passes between a search and a commit) -- this query just
	// writes the result.
	ScheduleAppointment(ctx context.Context, arg ScheduleAppointmentParams) (Appointment, error)
	// Every filter is optional (sqlc.narg(x) is null or ...); passing none
	// returns every child (subject to include_deactivated/limit_count).
	//
	// Name matching uses pg_trgm's word_similarity rather than plain
	// similarity() or ILIKE: word_similarity scores how well the query matches
	// *part of* the field, so a short query like "jhon" can still match
	// "Johnathan" -- plain similarity() compares the whole strings and craters
	// when they're very different lengths, and ILIKE only catches exact
	// substrings, not typos. The 0.2 threshold is a literal in the query
	// rather than the pg_trgm.similarity_threshold GUC (the %/<% operators'
	// default is 0.3, too strict for short name fields, and overriding a GUC
	// per-query risks leaking to the next query on a pooled connection).
	SearchChildren(ctx context.Context, arg SearchChildrenParams) ([]Child, error)
	// Existing-family lookup, primarily to catch duplicates before creating a
	// new family record for what's actually an existing one -- the legacy app
	// had this exact problem badly enough to need three separate hand-run
	// merge/dedupe SQL scripts. Matches if any guardian on the family matches
	// the name/email/phone filters, or the family's own address fields match.
	// A family with no guardians yet can't match on guardian filters (inner
	// join); that's fine since a family is always created together with its
	// first guardian in normal use.
	//
	// Results are ordered by id rather than name-match quality: DISTINCT
	// requires ORDER BY expressions to be in the select list, and this is a
	// "review a handful of candidates" tool for staff, not a ranked search --
	// ranking isn't worth the extra query complexity here.
	SearchFamilies(ctx context.Context, arg SearchFamiliesParams) ([]Family, error)
	// Candidate pool for "add an existing person to this lab" -- same
	// word_similarity name-matching pattern as SearchChildren/
	// SearchFamilies (see children.sql), scoped to active users who
	// aren't already a member of this lab.
	SearchUsersNotInLab(ctx context.Context, arg SearchUsersNotInLabParams) ([]User, error)
	// Mirrors ReleaseAppointment's status guard: only while an appointment
	// is still unscheduled or scheduled-but-not-yet-arrived does requesting
	// a dedicated greeter mean anything -- an arrived/released/etc.
	// appointment's staff assignment is already final (or moot).
	SetAppointmentWantsGreeter(ctx context.Context, arg SetAppointmentWantsGreeterParams) (Appointment, error)
	// Mirrors SetExperimentRoleSitter: a dedicated action, not part of
	// UpdateExperimentRole, with its own constraint (at most one greeter
	// role per lab, enforced by a partial unique index), the same
	// deactivated-role guard on setting true, and the same
	// always-allow-unset behavior.
	SetExperimentRoleGreeter(ctx context.Context, arg SetExperimentRoleGreeterParams) (ExperimentRole, error)
	// Dedicated action rather than part of UpdateExperimentRole: designating
	// the sitter role is a distinct decision from renaming a role. The
	// partial unique index (at most one sitter role per lab) rejects setting
	// a second role true while one's already set -- the caller must unset the
	// old one first, this doesn't swap automatically. Setting true is
	// rejected (zero rows) for an already-deactivated role -- the caller
	// (handleSetExperimentRoleSitter) checks this first for a clean 400
	// rather than a confusing 404; unsetting (false) is always allowed
	// regardless of deactivated status, to clean up any stale flag.
	SetExperimentRoleSitter(ctx context.Context, arg SetExperimentRoleSitterParams) (ExperimentRole, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// :one (RETURNING), not :exec, so granting/revoking admin on a
	// nonexistent id 404s instead of silently reporting success.
	SetUserPlatformAdmin(ctx context.Context, arg SetUserPlatformAdminParams) (User, error)
	// Backfills the link the first time an existing local-password account
	// signs in via SSO -- matched by email at that point, not (issuer, sub)
	// (which didn't exist on the row yet).
	SetUserSSOIdentity(ctx context.Context, arg SetUserSSOIdentityParams) error
	TouchSessionLastSeen(ctx context.Context, id int64) error
	UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error)
	UpdateCondition(ctx context.Context, arg UpdateConditionParams) (Condition, error)
	UpdateConditionValue(ctx context.Context, arg UpdateConditionValueParams) (ConditionValue, error)
	UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error)
	UpdateExperiment(ctx context.Context, arg UpdateExperimentParams) (Experiment, error)
	UpdateExperimentRole(ctx context.Context, arg UpdateExperimentRoleParams) (ExperimentRole, error)
	UpdateExperimentType(ctx context.Context, arg UpdateExperimentTypeParams) (ExperimentType, error)
	UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error)
	UpdateGrant(ctx context.Context, arg UpdateGrantParams) (Grant, error)
	UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error)
	UpdateLabMembership(ctx context.Context, arg UpdateLabMembershipParams) (LabMembership, error)
	UpdateNewsletter(ctx context.Context, arg UpdateNewsletterParams) (Newsletter, error)
	UpdateProtocol(ctx context.Context, arg UpdateProtocolParams) (Protocol, error)
	UpdateZipCode(ctx context.Context, arg UpdateZipCodeParams) (Zipcode, error)
	// last_run_at is always Postgres's own now(), not a caller-supplied
	// timestamp: it gets compared against audit_events.occurred_at (also
	// stamped by Postgres's now()) in ListChangedAppointmentIDsSince, and
	// comparing a value from the calling process's clock against one from
	// Postgres's clock is vulnerable to real (if small) clock skew between
	// the two -- caught by TestStaffDigestFlow_Integration flaking on
	// exactly this before this query was written this way.
	UpsertJobLastRun(ctx context.Context, jobName string) error
	// Child counts by mailing zip code, optionally filtered by recruitment
	// source, annotated with the lab's recruiting-priority tier for that zip
	// when one is configured. Child counts are computed globally (children
	// aren't lab-scoped -- the established shared-participant-pool design);
	// only the priority annotation comes from this lab's zipcodes lookup.
	ZipCodesReport(ctx context.Context, arg ZipCodesReportParams) ([]ZipCodesReportRow, error)
}

var _ Querier = (*Queries)(nil)
