// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recruitment_sources.sql

package db

import (
	"context"
)

const createRecruitmentSource = `-- name: CreateRecruitmentSource :one
insert into recruitment_sources (name) values ($1)
returning id, name, active
`

func (q *Queries) CreateRecruitmentSource(ctx context.Context, name string) (RecruitmentSource, error) {
	row := q.db.QueryRow(ctx, createRecruitmentSource, name)
	var i RecruitmentSource
	err := row.Scan(&i.ID, &i.Name, &i.Active)
	return i, err
}

const listActiveRecruitmentSources = `-- name: ListActiveRecruitmentSources :many
select id, name, active from recruitment_sources where active order by name
`

func (q *Queries) ListActiveRecruitmentSources(ctx context.Context) ([]RecruitmentSource, error) {
	rows, err := q.db.Query(ctx, listActiveRecruitmentSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecruitmentSource
	for rows.Next() {
		var i RecruitmentSource
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
