// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobLastRun = `-- name: GetJobLastRun :one
select last_run_at from scheduled_job_runs where job_name = $1
`

func (q *Queries) GetJobLastRun(ctx context.Context, jobName string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getJobLastRun, jobName)
	var last_run_at pgtype.Timestamptz
	err := row.Scan(&last_run_at)
	return last_run_at, err
}

const listAppointmentsDueForReminder = `-- name: ListAppointmentsDueForReminder :many
select
    appointments.id as appointment_id,
    appointments.schedule_date,
    appointments.schedule_time_start,
    experiments.name as experiment_name,
    children.first_name as child_first_name,
    children.last_name as child_last_name,
    -- coalesced to '' rather than left nullable: sqlc's static analysis
    -- doesn't propagate the nullability a LEFT JOIN LATERAL introduces
    -- when a family has zero guardians, so an uncoalesced column here
    -- would generate a plain (non-pointer) Go string that panics on scan
    -- when the row is genuinely NULL. '' also matches this codebase's
    -- existing "empty string means absent" convention for guardian
    -- fields (see guardians.email's own not-null-default-'' column).
    coalesce(guardian.email, '')::text as guardian_email,
    coalesce(guardian.first_name, '')::text as guardian_first_name,
    coalesce(guardian.last_name, '')::text as guardian_last_name
from appointments
join experiments on experiments.id = appointments.experiment_id
join children on children.id = appointments.child_id
join families on families.id = children.family_id
left join lateral (
    select g.email, g.first_name, g.last_name
    from guardians g
    where g.family_id = families.id
    order by g.id
    limit 1
) as guardian on true
where appointments.status = 'pending'
  and appointments.reminder_sent_at is null
  and (appointments.schedule_date + appointments.schedule_time_start)::timestamp <= $1::timestamp
order by appointments.schedule_date, appointments.schedule_time_start
`

type ListAppointmentsDueForReminderRow struct {
	AppointmentID     int64       `json:"appointment_id"`
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	ScheduleTimeStart pgtype.Time `json:"schedule_time_start"`
	ExperimentName    string      `json:"experiment_name"`
	ChildFirstName    string      `json:"child_first_name"`
	ChildLastName     string      `json:"child_last_name"`
	GuardianEmail     string      `json:"guardian_email"`
	GuardianFirstName string      `json:"guardian_first_name"`
	GuardianLastName  string      `json:"guardian_last_name"`
}

// Pending, not-yet-reminded appointments starting at or before the given
// cutoff (now + lead time), with the family's representative (lowest-id)
// guardian -- same idiom ListEligibleFamiliesForNewsletter uses. A
// family with no guardians at all (guardian_email null) is left for the
// caller to skip and log, not silently dropped here.
func (q *Queries) ListAppointmentsDueForReminder(ctx context.Context, dueBefore pgtype.Timestamp) ([]ListAppointmentsDueForReminderRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsDueForReminder, dueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsDueForReminderRow
	for rows.Next() {
		var i ListAppointmentsDueForReminderRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.ScheduleDate,
			&i.ScheduleTimeStart,
			&i.ExperimentName,
			&i.ChildFirstName,
			&i.ChildLastName,
			&i.GuardianEmail,
			&i.GuardianFirstName,
			&i.GuardianLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangedAppointmentIDsSince = `-- name: ListChangedAppointmentIDsSince :many
select coalesce(entity_id, 0)::bigint as appointment_id
from audit_events
where entity_type = 'appointment'
  and action = any($1::text[])
  and occurred_at > $2
  and entity_id is not null
group by entity_id
`

type ListChangedAppointmentIDsSinceParams struct {
	Actions []string           `json:"actions"`
	Since   pgtype.Timestamptz `json:"since"`
}

// Distinct appointment IDs with a relevant audit event since the digest's
// last run -- replaces legacy's change_status dirty-flag column with a
// query over the audit log this project already maintains as a hard
// requirement. entity_id is forced non-null via coalesce (safe: the
// where clause already excludes null entity_id) so the Go side gets a
// plain int64, not a pointer.
func (q *Queries) ListChangedAppointmentIDsSince(ctx context.Context, arg ListChangedAppointmentIDsSinceParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listChangedAppointmentIDsSince, arg.Actions, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var appointment_id int64
		if err := rows.Scan(&appointment_id); err != nil {
			return nil, err
		}
		items = append(items, appointment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAppointmentsForUserInLab = `-- name: ListPendingAppointmentsForUserInLab :many
select
    appointments.id as appointment_id,
    appointments.schedule_date,
    appointments.schedule_time_start,
    experiments.name as experiment_name,
    children.first_name as child_first_name,
    children.last_name as child_last_name,
    string_agg(distinct experiment_roles.name, ', ')::text as role_names
from appointments
join experiments on experiments.id = appointments.experiment_id
join children on children.id = appointments.child_id
join appointment_experimenters on appointment_experimenters.appointment_id = appointments.id
join experiment_roles on experiment_roles.id = appointment_experimenters.experiment_role_id
where experiments.lab_id = $1
  and appointments.status = 'pending'
  and appointments.schedule_date >= $2
  and exists (
      select 1 from appointment_experimenters assigned
      where assigned.appointment_id = appointments.id and assigned.user_id = $3
  )
group by appointments.id, appointments.schedule_date, appointments.schedule_time_start,
         experiments.name, children.first_name, children.last_name
order by appointments.schedule_date, appointments.schedule_time_start
`

type ListPendingAppointmentsForUserInLabParams struct {
	LabID  int64       `json:"lab_id"`
	Today  pgtype.Date `json:"today"`
	UserID int64       `json:"user_id"`
}

type ListPendingAppointmentsForUserInLabRow struct {
	AppointmentID     int64       `json:"appointment_id"`
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	ScheduleTimeStart pgtype.Time `json:"schedule_time_start"`
	ExperimentName    string      `json:"experiment_name"`
	ChildFirstName    string      `json:"child_first_name"`
	ChildLastName     string      `json:"child_last_name"`
	RoleNames         string      `json:"role_names"`
}

// One recipient's current upcoming Pending schedule in one lab -- the
// digest email body. Filters to appointments the given user is assigned
// to (via exists), but aggregates role names across every experimenter
// on the appointment, not just the recipient's own role, matching
// legacy's "(roles)" showing the whole assigned team for context.
func (q *Queries) ListPendingAppointmentsForUserInLab(ctx context.Context, arg ListPendingAppointmentsForUserInLabParams) ([]ListPendingAppointmentsForUserInLabRow, error) {
	rows, err := q.db.Query(ctx, listPendingAppointmentsForUserInLab, arg.LabID, arg.Today, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingAppointmentsForUserInLabRow
	for rows.Next() {
		var i ListPendingAppointmentsForUserInLabRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.ScheduleDate,
			&i.ScheduleTimeStart,
			&i.ExperimentName,
			&i.ChildFirstName,
			&i.ChildLastName,
			&i.RoleNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipientsForAppointments = `-- name: ListRecipientsForAppointments :many
select distinct
    users.id as user_id,
    users.email,
    users.first_name,
    users.last_name,
    experiments.lab_id,
    labs.short_name as lab_short_name
from appointment_experimenters
join appointments on appointments.id = appointment_experimenters.appointment_id
join experiments on experiments.id = appointments.experiment_id
join labs on labs.id = experiments.lab_id
join users on users.id = appointment_experimenters.user_id
where appointment_experimenters.appointment_id = any($1::bigint[])
`

type ListRecipientsForAppointmentsRow struct {
	UserID       int64  `json:"user_id"`
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	LabID        int64  `json:"lab_id"`
	LabShortName string `json:"lab_short_name"`
}

// Distinct (staff member, lab) pairs assigned to any of the given
// appointments -- the digest's recipients. Recipients come from
// appointment_experimenters (who's actually assigned), not from the
// audit event's actor (who might be an admin scheduling on someone
// else's behalf).
func (q *Queries) ListRecipientsForAppointments(ctx context.Context, appointmentIds []int64) ([]ListRecipientsForAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listRecipientsForAppointments, appointmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipientsForAppointmentsRow
	for rows.Next() {
		var i ListRecipientsForAppointmentsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.LabID,
			&i.LabShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppointmentReminderSent = `-- name: MarkAppointmentReminderSent :exec
update appointments set reminder_sent_at = now() where id = $1
`

func (q *Queries) MarkAppointmentReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAppointmentReminderSent, id)
	return err
}

const upsertJobLastRun = `-- name: UpsertJobLastRun :exec
insert into scheduled_job_runs (job_name, last_run_at)
values ($1, now())
on conflict (job_name) do update set last_run_at = now()
`

// last_run_at is always Postgres's own now(), not a caller-supplied
// timestamp: it gets compared against audit_events.occurred_at (also
// stamped by Postgres's now()) in ListChangedAppointmentIDsSince, and
// comparing a value from the calling process's clock against one from
// Postgres's clock is vulnerable to real (if small) clock skew between
// the two -- caught by TestStaffDigestFlow_Integration flaking on
// exactly this before this query was written this way.
func (q *Queries) UpsertJobLastRun(ctx context.Context, jobName string) error {
	_, err := q.db.Exec(ctx, upsertJobLastRun, jobName)
	return err
}
