// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demographicsReport = `-- name: DemographicsReport :many
select
    children.id as child_id,
    children.first_name,
    children.last_name,
    children.sex,
    children.race_ethnicity,
    appointments.schedule_date,
    (extract(year from age(appointments.schedule_date, children.birth_date)) * 12
        + extract(month from age(appointments.schedule_date, children.birth_date)))::float8 as age_months,
    coalesce(
        (select guardians.education from guardians
         where guardians.family_id = children.family_id
         order by guardians.id
         limit 1),
        'unknown'
    )::text as guardian_education
from children
join appointments on appointments.child_id = children.id
where appointments.experiment_id = $1
  and appointments.status = 'arrived'
  and appointments.schedule_date between $2 and $3
order by appointments.schedule_date
`

type DemographicsReportParams struct {
	ExperimentID int64       `json:"experiment_id"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
}

type DemographicsReportRow struct {
	ChildID           int64       `json:"child_id"`
	FirstName         string      `json:"first_name"`
	LastName          string      `json:"last_name"`
	Sex               string      `json:"sex"`
	RaceEthnicity     []string    `json:"race_ethnicity"`
	ScheduleDate      pgtype.Date `json:"schedule_date"`
	AgeMonths         float64     `json:"age_months"`
	GuardianEducation string      `json:"guardian_education"`
}

// Per-child listing of 'arrived' appointments for one experiment in a
// date range, with age at the appointment (in months) and the family's
// first (lowest-id) guardian's education level. Handler computes summary
// counts over these rows in Go rather than a second query.
func (q *Queries) DemographicsReport(ctx context.Context, arg DemographicsReportParams) ([]DemographicsReportRow, error) {
	rows, err := q.db.Query(ctx, demographicsReport, arg.ExperimentID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemographicsReportRow
	for rows.Next() {
		var i DemographicsReportRow
		if err := rows.Scan(
			&i.ChildID,
			&i.FirstName,
			&i.LastName,
			&i.Sex,
			&i.RaceEthnicity,
			&i.ScheduleDate,
			&i.AgeMonths,
			&i.GuardianEducation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hRCReportByProtocol = `-- name: HRCReportByProtocol :many
select
    protocols.id as protocol_id,
    protocols.name as protocol_name,
    count(distinct appointments.child_id) as child_count
from protocols
left join experiments on experiments.protocol_id = protocols.id
left join appointments on appointments.experiment_id = experiments.id
    and appointments.status = 'arrived'
    and appointments.schedule_date between $1 and $2
where protocols.lab_id = $3
group by protocols.id, protocols.name
order by protocols.name
`

type HRCReportByProtocolParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	LabID     int64       `json:"lab_id"`
}

type HRCReportByProtocolRow struct {
	ProtocolID   int64  `json:"protocol_id"`
	ProtocolName string `json:"protocol_name"`
	ChildCount   int64  `json:"child_count"`
}

// Distinct-child 'arrived' counts per protocol in a date range, for the
// lab's Human Research Committee (IRB) reporting.
func (q *Queries) HRCReportByProtocol(ctx context.Context, arg HRCReportByProtocolParams) ([]HRCReportByProtocolRow, error) {
	rows, err := q.db.Query(ctx, hRCReportByProtocol, arg.StartDate, arg.EndDate, arg.LabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HRCReportByProtocolRow
	for rows.Next() {
		var i HRCReportByProtocolRow
		if err := rows.Scan(&i.ProtocolID, &i.ProtocolName, &i.ChildCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hRCReportTotal = `-- name: HRCReportTotal :one
select count(distinct appointments.child_id) as child_count
from appointments
join experiments on experiments.id = appointments.experiment_id
where experiments.lab_id = $1
  and appointments.status = 'arrived'
  and appointments.schedule_date between $2 and $3
`

type HRCReportTotalParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// All-protocols total for the same window, lab-wide (including
// experiments with no protocol assigned).
func (q *Queries) HRCReportTotal(ctx context.Context, arg HRCReportTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, hRCReportTotal, arg.LabID, arg.StartDate, arg.EndDate)
	var child_count int64
	err := row.Scan(&child_count)
	return child_count, err
}

const nIHParticipantReport = `-- name: NIHParticipantReport :many
select distinct on (children.id)
    children.id as child_id,
    children.sex,
    children.race_ethnicity,
    children.birth_date,
    appointments.schedule_date
from children
join appointments on appointments.child_id = children.id
join experiments on experiments.id = appointments.experiment_id
left join experiment_grants on experiment_grants.experiment_id = experiments.id
where experiments.lab_id = $1
  and appointments.status = 'arrived'
  and appointments.schedule_date between $2 and $3
  and ($4::bigint is null or experiment_grants.grant_id = $4)
order by children.id, appointments.schedule_date
`

type NIHParticipantReportParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	GrantID   *int64      `json:"grant_id"`
}

type NIHParticipantReportRow struct {
	ChildID       int64       `json:"child_id"`
	Sex           string      `json:"sex"`
	RaceEthnicity []string    `json:"race_ethnicity"`
	BirthDate     pgtype.Date `json:"birth_date"`
	ScheduleDate  pgtype.Date `json:"schedule_date"`
}

// One row per distinct child with an 'arrived' appointment in range --
// the current-shape NIH participant-level data template, which must be
// submitted as a flat CSV (one row per participant) rather than the
// old aggregate category/sex crosstab. Race/ethnicity/sex label
// mapping and age-unit computation happen in Go (see nih_report.go),
// not here, so a null birth_date can be handled explicitly rather than
// relying on sqlc's nullability inference over a computed expression.
// When a child has more than one qualifying appointment in the window,
// the earliest one is used for age-at-visit (distinct on + order by
// schedule_date), matching the distinct-child counting the old
// aggregate queries already used.
func (q *Queries) NIHParticipantReport(ctx context.Context, arg NIHParticipantReportParams) ([]NIHParticipantReportRow, error) {
	rows, err := q.db.Query(ctx, nIHParticipantReport,
		arg.LabID,
		arg.StartDate,
		arg.EndDate,
		arg.GrantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NIHParticipantReportRow
	for rows.Next() {
		var i NIHParticipantReportRow
		if err := rows.Scan(
			&i.ChildID,
			&i.Sex,
			&i.RaceEthnicity,
			&i.BirthDate,
			&i.ScheduleDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zipCodesReport = `-- name: ZipCodesReport :many
select
    families.zip,
    zipcodes.priority,
    count(*) as child_count
from children
join families on families.id = children.family_id
left join zipcodes on zipcodes.zip_code = families.zip
    and zipcodes.lab_id = $1
    and zipcodes.deactivated_at is null
where children.deactivated_at is null
  and ($2::bigint is null or children.recruitment_source_id = $2)
group by families.zip, zipcodes.priority
order by families.zip
`

type ZipCodesReportParams struct {
	LabID               int64  `json:"lab_id"`
	RecruitmentSourceID *int64 `json:"recruitment_source_id"`
}

type ZipCodesReportRow struct {
	Zip        string  `json:"zip"`
	Priority   *string `json:"priority"`
	ChildCount int64   `json:"child_count"`
}

// Child counts by mailing zip code, optionally filtered by recruitment
// source, annotated with the lab's recruiting-priority tier for that zip
// when one is configured. Child counts are computed globally (children
// aren't lab-scoped -- the established shared-participant-pool design);
// only the priority annotation comes from this lab's zipcodes lookup.
func (q *Queries) ZipCodesReport(ctx context.Context, arg ZipCodesReportParams) ([]ZipCodesReportRow, error) {
	rows, err := q.db.Query(ctx, zipCodesReport, arg.LabID, arg.RecruitmentSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZipCodesReportRow
	for rows.Next() {
		var i ZipCodesReportRow
		if err := rows.Scan(&i.Zip, &i.Priority, &i.ChildCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
