// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_blockings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleBlocking = `-- name: CreateScheduleBlocking :one
insert into schedule_blockings (lab_id, date, start_time, end_time, reason)
values ($1, $2, $3, $4, $5)
returning id, lab_id, date, start_time, end_time, reason, deactivated_at, created_at, updated_at
`

type CreateScheduleBlockingParams struct {
	LabID     int64       `json:"lab_id"`
	Date      pgtype.Date `json:"date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Reason    string      `json:"reason"`
}

func (q *Queries) CreateScheduleBlocking(ctx context.Context, arg CreateScheduleBlockingParams) (ScheduleBlocking, error) {
	row := q.db.QueryRow(ctx, createScheduleBlocking,
		arg.LabID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i ScheduleBlocking
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateScheduleBlocking = `-- name: DeactivateScheduleBlocking :exec
update schedule_blockings set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateScheduleBlocking(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateScheduleBlocking, id)
	return err
}

const getScheduleBlockingByID = `-- name: GetScheduleBlockingByID :one
select id, lab_id, date, start_time, end_time, reason, deactivated_at, created_at, updated_at from schedule_blockings where id = $1
`

func (q *Queries) GetScheduleBlockingByID(ctx context.Context, id int64) (ScheduleBlocking, error) {
	row := q.db.QueryRow(ctx, getScheduleBlockingByID, id)
	var i ScheduleBlocking
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduleBlockingsByLab = `-- name: ListScheduleBlockingsByLab :many
select id, lab_id, date, start_time, end_time, reason, deactivated_at, created_at, updated_at from schedule_blockings
where lab_id = $1 and deactivated_at is null
order by date, start_time
`

func (q *Queries) ListScheduleBlockingsByLab(ctx context.Context, labID int64) ([]ScheduleBlocking, error) {
	rows, err := q.db.Query(ctx, listScheduleBlockingsByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleBlocking
	for rows.Next() {
		var i ScheduleBlocking
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleBlockingsForDateRange = `-- name: ListScheduleBlockingsForDateRange :many
select id, lab_id, date, start_time, end_time, reason, deactivated_at, created_at, updated_at from schedule_blockings
where lab_id = $1
  and date between $2 and $3
  and deactivated_at is null
`

type ListScheduleBlockingsForDateRangeParams struct {
	LabID     int64       `json:"lab_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// One query for a whole multi-day search range, rather than one call per
// candidate day -- the caller groups rows by date in Go.
func (q *Queries) ListScheduleBlockingsForDateRange(ctx context.Context, arg ListScheduleBlockingsForDateRangeParams) ([]ScheduleBlocking, error) {
	rows, err := q.db.Query(ctx, listScheduleBlockingsForDateRange, arg.LabID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleBlocking
	for rows.Next() {
		var i ScheduleBlocking
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
