// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (token_hash, user_id, expires_at, ip_address, user_agent)
values (
    $1,
    $2,
    $3,
    $4,
    $5
)
returning id, token_hash, user_id, created_at, expires_at, last_seen_at, ip_address, user_agent, revoked_at
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, token_hash, user_id, created_at, expires_at, last_seen_at, ip_address, user_agent, revoked_at from sessions where token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
update sessions set last_seen_at = now() where id = $1
`

func (q *Queries) TouchSessionLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchSessionLastSeen, id)
	return err
}
