// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email, first_name, last_name, password_hash, is_platform_admin, sso_issuer, sso_subject)
values (
    lower($1),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject
`

type CreateUserParams struct {
	Email           string  `json:"email"`
	FirstName       string  `json:"first_name"`
	LastName        string  `json:"last_name"`
	PasswordHash    *string `json:"password_hash"`
	IsPlatformAdmin bool    `json:"is_platform_admin"`
	SsoIssuer       *string `json:"sso_issuer"`
	SsoSubject      *string `json:"sso_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.IsPlatformAdmin,
		arg.SsoIssuer,
		arg.SsoSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserBySSOIdentity = `-- name: GetUserBySSOIdentity :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where sso_issuer = $1 and sso_subject = $2
`

type GetUserBySSOIdentityParams struct {
	SsoIssuer  *string `json:"sso_issuer"`
	SsoSubject *string `json:"sso_subject"`
}

func (q *Queries) GetUserBySSOIdentity(ctx context.Context, arg GetUserBySSOIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySSOIdentity, arg.SsoIssuer, arg.SsoSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const setUserSSOIdentity = `-- name: SetUserSSOIdentity :exec
update users set sso_issuer = $1, sso_subject = $2 where id = $3
`

type SetUserSSOIdentityParams struct {
	SsoIssuer  *string `json:"sso_issuer"`
	SsoSubject *string `json:"sso_subject"`
	ID         int64   `json:"id"`
}

// Backfills the link the first time an existing local-password account
// signs in via SSO -- matched by email at that point, not (issuer, sub)
// (which didn't exist on the row yet).
func (q *Queries) SetUserSSOIdentity(ctx context.Context, arg SetUserSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, setUserSSOIdentity, arg.SsoIssuer, arg.SsoSubject, arg.ID)
	return err
}
