// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email, first_name, last_name, password_hash, is_platform_admin)
values (
    lower($1),
    $2,
    $3,
    $4,
    $5
)
returning id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at
`

type CreateUserParams struct {
	Email           string  `json:"email"`
	FirstName       string  `json:"first_name"`
	LastName        string  `json:"last_name"`
	PasswordHash    *string `json:"password_hash"`
	IsPlatformAdmin bool    `json:"is_platform_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.IsPlatformAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at from users where lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
