// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (email, first_name, last_name, password_hash, is_platform_admin, sso_issuer, sso_subject)
values (
    lower($1),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject
`

type CreateUserParams struct {
	Email           string  `json:"email"`
	FirstName       string  `json:"first_name"`
	LastName        string  `json:"last_name"`
	PasswordHash    *string `json:"password_hash"`
	IsPlatformAdmin bool    `json:"is_platform_admin"`
	SsoIssuer       *string `json:"sso_issuer"`
	SsoSubject      *string `json:"sso_subject"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.IsPlatformAdmin,
		arg.SsoIssuer,
		arg.SsoSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
update users set deactivated_at = now() where id = $1 returning id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject
`

// :one (RETURNING), not :exec, so deactivating a nonexistent id 404s
// instead of silently reporting success -- same reasoning as
// RemoveLabMembership.
func (q *Queries) DeactivateUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const getUserBySSOIdentity = `-- name: GetUserBySSOIdentity :one
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users where sso_issuer = $1 and sso_subject = $2
`

type GetUserBySSOIdentityParams struct {
	SsoIssuer  *string `json:"sso_issuer"`
	SsoSubject *string `json:"sso_subject"`
}

func (q *Queries) GetUserBySSOIdentity(ctx context.Context, arg GetUserBySSOIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySSOIdentity, arg.SsoIssuer, arg.SsoSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject from users order by created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
			&i.SsoIssuer,
			&i.SsoSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
update users set password_hash = $1 where id = $2
`

type SetUserPasswordParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserPlatformAdmin = `-- name: SetUserPlatformAdmin :one
update users set is_platform_admin = $1 where id = $2 returning id, email, first_name, last_name, password_hash, is_platform_admin, created_at, updated_at, deactivated_at, sso_issuer, sso_subject
`

type SetUserPlatformAdminParams struct {
	IsPlatformAdmin bool  `json:"is_platform_admin"`
	ID              int64 `json:"id"`
}

// :one (RETURNING), not :exec, so granting/revoking admin on a
// nonexistent id 404s instead of silently reporting success.
func (q *Queries) SetUserPlatformAdmin(ctx context.Context, arg SetUserPlatformAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPlatformAdmin, arg.IsPlatformAdmin, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.SsoIssuer,
		&i.SsoSubject,
	)
	return i, err
}

const setUserSSOIdentity = `-- name: SetUserSSOIdentity :exec
update users set sso_issuer = $1, sso_subject = $2 where id = $3
`

type SetUserSSOIdentityParams struct {
	SsoIssuer  *string `json:"sso_issuer"`
	SsoSubject *string `json:"sso_subject"`
	ID         int64   `json:"id"`
}

// Backfills the link the first time an existing local-password account
// signs in via SSO -- matched by email at that point, not (issuer, sub)
// (which didn't exist on the row yet).
func (q *Queries) SetUserSSOIdentity(ctx context.Context, arg SetUserSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, setUserSSOIdentity, arg.SsoIssuer, arg.SsoSubject, arg.ID)
	return err
}
