// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zipcodes.sql

package db

import (
	"context"
)

const createZipCode = `-- name: CreateZipCode :one
insert into zipcodes (lab_id, zip_code, priority) values ($1, $2, $3)
returning id, lab_id, zip_code, priority, deactivated_at, created_at, updated_at
`

type CreateZipCodeParams struct {
	LabID    int64  `json:"lab_id"`
	ZipCode  string `json:"zip_code"`
	Priority string `json:"priority"`
}

func (q *Queries) CreateZipCode(ctx context.Context, arg CreateZipCodeParams) (Zipcode, error) {
	row := q.db.QueryRow(ctx, createZipCode, arg.LabID, arg.ZipCode, arg.Priority)
	var i Zipcode
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.ZipCode,
		&i.Priority,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateZipCode = `-- name: DeactivateZipCode :exec
update zipcodes set deactivated_at = now() where id = $1
`

func (q *Queries) DeactivateZipCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateZipCode, id)
	return err
}

const getZipCodeByID = `-- name: GetZipCodeByID :one
select id, lab_id, zip_code, priority, deactivated_at, created_at, updated_at from zipcodes where id = $1
`

func (q *Queries) GetZipCodeByID(ctx context.Context, id int64) (Zipcode, error) {
	row := q.db.QueryRow(ctx, getZipCodeByID, id)
	var i Zipcode
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.ZipCode,
		&i.Priority,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZipCodesByLab = `-- name: ListZipCodesByLab :many
select id, lab_id, zip_code, priority, deactivated_at, created_at, updated_at from zipcodes where lab_id = $1 order by zip_code
`

func (q *Queries) ListZipCodesByLab(ctx context.Context, labID int64) ([]Zipcode, error) {
	rows, err := q.db.Query(ctx, listZipCodesByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zipcode
	for rows.Next() {
		var i Zipcode
		if err := rows.Scan(
			&i.ID,
			&i.LabID,
			&i.ZipCode,
			&i.Priority,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZipCode = `-- name: UpdateZipCode :one
update zipcodes set zip_code = $1, priority = $2
where id = $3
returning id, lab_id, zip_code, priority, deactivated_at, created_at, updated_at
`

type UpdateZipCodeParams struct {
	ZipCode  string `json:"zip_code"`
	Priority string `json:"priority"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateZipCode(ctx context.Context, arg UpdateZipCodeParams) (Zipcode, error) {
	row := q.db.QueryRow(ctx, updateZipCode, arg.ZipCode, arg.Priority, arg.ID)
	var i Zipcode
	err := row.Scan(
		&i.ID,
		&i.LabID,
		&i.ZipCode,
		&i.Priority,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
